(function(){
  "use strict";
  const app=document.querySelector("[data-archive-notes-app]");if(!app)return;
  const esc=value=>window.ArchiveNoteMarkdown.escape(value),list=value=>Array.isArray(value)?value:[];
  async function getJson(path){const response=await fetch(path,{headers:{accept:"application/json"}}),payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||"The Archive did not answer.");error.status=response.status;throw error}return payload}
  function slugFromPath(){const parts=location.pathname.split("/").filter(Boolean);return parts[0]==="archive"&&parts[1]==="notes"&&parts[2]?decodeURIComponent(parts[2]):""}
  function dates(note){return `<div class="archive-note-dates">${note.source_created_at?`<span>Created ${esc(note.source_created_at==="2022-12-23T19:54:00-05:00"?"December 23, 2022 at 7:54 PM":note.source_created_at)}</span>`:""}${note.source_modified_at?`<span>Last edited ${esc(note.source_modified_at==="2023-11-26"?"November 26, 2023":note.source_modified_at)}</span>`:""}</div>`}
  function provenance(note){const copy=note.provenance_note||note.provenanceNote||"";return copy?`<p class="archive-note-provenance"><span>Archive note</span>${esc(copy)}</p>`:""}
  function card(note){return `<article class="archive-note-card"><a href="${esc(note.route)}"><span class="archive-note-card-media">${note.preview_url?`<img src="${esc(note.preview_url)}" alt="" loading="lazy">`:""}</span><span class="archive-note-card-copy"><span class="archive-kicker">${esc(note.note_type||"Archive note")}</span><h2>${esc(note.title)}</h2>${dates(note)}${note.excerpt?`<p>${esc(note.excerpt)}</p>`:""}</span></a></article>`}
  async function index(){const payload=await getJson("/api/archive/notes"),notes=list(payload.records);app.innerHTML=`<header class="archive-timeline-header site-hero site-hero--supporting"><div><span class="archive-kicker">Archive writing and evidence</span><h1 class="hero-title">Notes.</h1></div><div><p class="hero-descriptor">Complete sketches, ideas, and process entries that can connect to more than one work.</p><div class="archive-meta"><span>${notes.length} public ${notes.length===1?"note":"notes"}</span></div></div></header>${notes.length?`<section class="archive-notes-grid" aria-label="Public Archive Notes">${notes.map(card).join("")}</section>`:`<section class="archive-empty"><span class="archive-kicker">Notes forming</span><h2>No public Notes yet.</h2><p>Complete Note records will appear here after their text, attachments, and relationships are reviewed.</p></section>`}`}
  async function detail(slug){const payload=await getJson(`/api/archive/notes/${encodeURIComponent(slug)}`),note=payload.note||payload.record,assets=list(payload.assets),links=list(payload.links),origins=list(payload.origin_threads||payload.originThreads),breadcrumb=document.querySelector("[data-archive-note-breadcrumb]");breadcrumb.textContent=note.title;document.title=`${note.title} · Notes · Archive · the six.well construct`;const context=[...links.map(link=>`<li><span class="archive-label">${esc(link.relationship_role)}</span><a href="${esc(link.route||"/archive/")}">${esc(link.title||link.target_entity_id)}</a></li>`),...origins.map(origin=>`<li><span class="archive-label">Origin thread</span><a href="${esc(origin.route)}">${esc(origin.title)}</a></li>`)].join("");app.innerHTML=`<article><header class="archive-record-header site-hero site-hero--supporting"><div class="archive-record-heading"><div><span class="archive-kicker">${esc(note.note_type||"Archive note")}</span><h1 class="archive-record-title hero-title">${esc(note.title)}</h1></div><div class="archive-record-orientation"><p class="hero-descriptor">${esc(note.excerpt||"A complete public Note retained as its own Archive record.")}</p>${dates(note)}${provenance(note)}</div></div></header><div class="archive-note-layout"><section class="archive-note-reader" tabindex="0" role="region" aria-label="Complete note entry">${window.ArchiveNoteMarkdown.render(note.body_markdown,assets)}</section><aside class="archive-note-context"><h2>Connected within the Archive</h2>${context?`<ul class="archive-note-context-list">${context}</ul>`:"<p>No public links yet.</p>"}</aside></div></article>`;window.ArchiveNoteMarkdown.bindImageLightboxes(app)}
  const slug=slugFromPath();(slug?detail(slug):index()).catch(error=>{app.innerHTML=`<section class="archive-empty"><span class="archive-kicker">Note unavailable</span><h1>${error.status===404?"This Note is not public.":"The Notes could not be opened."}</h1><p>Please try again in a moment.</p></section>`});
})();
