(function(){
  "use strict";
  var app=document.getElementById("calendarSubmissionApp");
  if(!app)return;
  var mode=document.body.dataset.submissionMode||"create";
  var state={stage:0,files:[],media:[],turnstileId:null,token:"",submission:null,idempotencyKey:crypto.randomUUID()};
  var SUBJECTS=[["art","Art"],["art-making","Art making"],["film","Film"],["poetry-music","Poetry / music"],["technology","Technology"],["ai","AI"],["creative-technology","Creative technology"],["anthropology","Anthropology"],["engineering","Engineering"],["philosophy","Philosophy"]];
  var FORMATS=[["exhibition","Exhibition"],["screening","Screening"],["performance","Performance"],["experimental-event","Experimental event"],["lecture-talk","Lecture / talk"],["panel","Panel"],["workshop","Workshop"],["conference","Conference"]];
  var STAGES=["Event basics","Schedule + place","People + links","Admission + media","Contact + consent"];
  function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(character){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character];});}
  function val(id){var control=document.getElementById(id);return control?control.value.trim():"";}
  function checked(name){return Array.from(document.querySelectorAll('input[name="'+name+'"]:checked')).map(function(input){return input.value;});}
  function choice(name,items){return '<div class="choice-grid">'+items.map(function(item){return '<label><input type="checkbox" name="'+name+'" value="'+esc(item[0])+'"><span>'+esc(item[1])+'</span></label>';}).join("")+'</div>';}
  function shell(){
    app.innerHTML='<div class="submission-shell">'+(mode==="manage"?'<section class="submission-status-card" id="manageStatus"></section>':'')+
      '<ol class="submission-progress" aria-label="Submission progress">'+STAGES.map(function(label,index){return '<li data-progress="'+index+'"><span>Step '+(index+1)+'</span>'+label+'</li>';}).join("")+'</ol>'+
      '<form class="submission-form" id="calendarSubmissionForm" novalidate><div class="validation-summary" id="validationSummary" role="alert" tabindex="-1"></div>'+
      '<fieldset class="submission-stage" data-stage="0"><legend>Event basics</legend><p class="stage-intro">Start with what the event is. Corrections follow the same path and stay private until Studio reviews selected changes.</p><div class="field-grid">'+
      '<div class="field-group is-wide"><span>What are you sending? *</span><div class="choice-grid"><label><input type="radio" name="kind" value="new" checked><span>New event</span></label><label><input type="radio" name="kind" value="correction"><span>Correction</span></label></div></div>'+
      '<label class="is-wide correction-only" hidden><span>Current calendar listing URL *</span><input id="targetUrl" type="url" inputmode="url" placeholder="https://thesixwellconstruct.com/calendar/…"></label><label class="is-wide correction-only" hidden><span>What should change? *</span><textarea id="correctionSummary"></textarea></label>'+
      '<label class="is-wide"><span>Event title *</span><input id="eventTitle" autocomplete="off" required></label><label class="is-wide"><span>Factual description *</span><textarea id="description" required placeholder="What happens, who it is for, and the factual program details."></textarea></label>'+
      '<label><span>Event structure</span><select id="eventStructure"><option value="single">Single event</option><option value="exhibition">Exhibition / on view</option><option value="series">Series / multiple programs</option></select></label><label class="check-line"><input id="experimental" type="checkbox"><span>Experimental creative event</span></label>'+
      '<div class="field-group is-wide"><span>Creative subjects *</span>'+choice("subjects",SUBJECTS)+'</div><div class="field-group is-wide"><span>Formats</span>'+choice("formats",FORMATS)+'</div></div></fieldset>'+
      '<fieldset class="submission-stage" data-stage="1" hidden><legend>Schedule + place</legend><p class="stage-intro">Use Atlanta local dates and times. Exhibitions can use a first and last date; related programs can be added in the next stage.</p><div class="field-grid">'+
      '<label><span>Schedule type</span><select id="dateKind"><option value="timed">Date + time</option><option value="all_day">All day</option><option value="date_range">Date range</option></select></label><label><span>Time zone</span><input id="timezone" value="America/New_York" readonly></label><label><span id="startsLabel">Starts *</span><input id="startsAt" type="datetime-local" required></label><label><span id="endsLabel">Ends</span><input id="endsAt" type="datetime-local"></label><label><span>Doors (optional)</span><input id="doorsAt" type="datetime-local"></label><label class="check-line"><input id="online" type="checkbox"><span>This is an online event</span></label><label><span>Venue *</span><input id="venueName" autocomplete="organization"></label><label><span>Venue website</span><input id="venueUrl" type="url" inputmode="url"></label><label class="is-wide"><span>Venue address</span><input id="venueAddress" autocomplete="street-address"></label><label><span>City</span><input id="city" value="Atlanta"></label><label><span>State</span><input id="region" value="GA" maxlength="2"></label><label class="check-line is-wide"><input id="atlantaConfirmed" type="checkbox"><span>I confirm this is an Atlanta metro event. *</span></label></div></fieldset>'+
      '<fieldset class="submission-stage" data-stage="2" hidden><legend>People + links</legend><p class="stage-intro">Add the primary organizer, then credit artists, participants, additional organizers, and venues. Role labels can describe what each person contributes.</p><div class="field-grid"><label><span>Primary organizer *</span><input id="organizer" autocomplete="organization"></label><label><span>Organizer website</span><input id="organizerUrl" type="url" inputmode="url"></label><div class="is-wide"><div class="submission-repeaters" id="peopleRows"></div><button class="compact-button" id="addPerson" type="button">Add person or organization</button></div><div class="is-wide"><h3>Related programs or series dates</h3><div class="submission-repeaters" id="occurrenceRows"></div><button class="compact-button" id="addOccurrence" type="button">Add related date</button></div></div></fieldset>'+
      '<fieldset class="submission-stage" data-stage="3" hidden><legend>Admission + media</legend><p class="stage-intro">An official event link, ticket or RSVP link, or at least one flyer is required. Submitted media stays private unless Studio deliberately promotes it.</p><div class="field-grid"><label><span>Admission *</span><select id="admissionType"><option value="">Choose one</option><option value="free">Free / walk in</option><option value="free_rsvp">Free / RSVP required</option><option value="paid">Paid ticket</option><option value="donation">Donation based</option><option value="restricted">Restricted / invitation only</option></select></label><label><span>Ticket or RSVP URL</span><input id="ticketUrl" type="url" inputmode="url"></label><label class="is-wide"><span>Official event URL</span><input id="sourceUrl" type="url" inputmode="url"></label><label class="is-wide"><span>Announcement or discovery URL</span><input id="discoveryUrl" type="url" inputmode="url"></label><label class="is-wide"><span>Admission details</span><textarea id="admissionNotes"></textarea></label><label class="is-wide"><span>Access requirements</span><textarea id="accessNotes"></textarea></label><label><span>Age information</span><input id="ageNotes"></label><label><span>Accessibility information</span><input id="accessibilityNotes"></label><div class="file-intake is-wide"><input id="flyerInput" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple><button class="file-picker" id="chooseFlyers" type="button">Choose flyers or images</button><p class="file-meta" id="fileCount">0 of 6 images staged. JPEG, PNG, WebP, or GIF; 15 MB each, 45 MB total.</p><div class="staged-files" id="stagedFiles"></div></div></div></fieldset>'+
      '<fieldset class="submission-stage" data-stage="4" hidden><legend>Contact + consent</legend><p class="stage-intro">Contact details and consent evidence remain private. They never enter public candidate snapshots, cards, APIs, media responses, search, or calendar feeds.</p><div class="field-grid"><label><span>Your name *</span><input id="submitterName" autocomplete="name"></label><label><span>Email *</span><input id="submitterEmail" type="email" autocomplete="email"></label><label><span>Phone</span><input id="submitterPhone" type="tel" autocomplete="tel"></label><label><span>Your relationship to the event</span><input id="submitterRelationship" placeholder="Organizer, artist, attendee, venue…"></label><label class="check-line is-wide"><input id="rightsConfirmed" type="checkbox"><span>I have permission to provide these event materials and flyers. *</span></label><label class="check-line is-wide"><input id="editorialConfirmed" type="checkbox"><span>I understand this is a private editorial suggestion and does not guarantee publication. *</span></label><label class="honeypot" aria-hidden="true"><span>Website</span><input id="website" tabindex="-1" autocomplete="off"></label>'+(mode==="create"?'<div class="turnstile-wrap is-wide" id="turnstileWrap"><p class="submission-help">Loading verification.</p></div>':'')+'</div></fieldset>'+
      '<div class="submission-actions"><button id="previousStage" type="button">Back</button><button id="nextStage" class="primary" type="button">Continue</button><button id="submitSubmission" class="primary" type="submit" hidden>'+(mode==="manage"?'Save changes':'Send for private review')+'</button></div></form></div>';
    bind();renderStage();
  }
  function bind(){
    var form=document.getElementById("calendarSubmissionForm");
    document.getElementById("previousStage").addEventListener("click",function(){state.stage=Math.max(0,state.stage-1);renderStage();});
    document.getElementById("nextStage").addEventListener("click",function(){var errors=stageErrors(state.stage);if(errors.length)return showErrors(errors);state.stage=Math.min(4,state.stage+1);renderStage();});
    form.addEventListener("submit",submit);
    form.addEventListener("change",function(event){if(event.target.name==="kind")document.querySelectorAll(".correction-only").forEach(function(item){item.hidden=event.target.value!=="correction";});if(event.target.id==="dateKind")syncDateKind();if(event.target.id==="online")syncOnline();});
    document.getElementById("addPerson").addEventListener("click",function(){addPerson({});});
    document.getElementById("addOccurrence").addEventListener("click",function(){addOccurrence({});});
    document.getElementById("chooseFlyers").addEventListener("click",function(){document.getElementById("flyerInput").click();});
    document.getElementById("flyerInput").addEventListener("change",stageFiles);
    document.getElementById("stagedFiles").addEventListener("click",fileAction);
    document.getElementById("peopleRows").addEventListener("click",removeRow);
    document.getElementById("occurrenceRows").addEventListener("click",removeRow);
    if(mode==="manage"){var status=document.getElementById("manageStatus");status.addEventListener("click",function(event){if(event.target.matches("[data-withdraw]"))withdraw();});}
  }
  function renderStage(){
    document.querySelectorAll("[data-stage]").forEach(function(item){item.hidden=Number(item.dataset.stage)!==state.stage;});
    document.querySelectorAll("[data-progress]").forEach(function(item){item.classList.toggle("is-current",Number(item.dataset.progress)===state.stage);});
    document.getElementById("previousStage").hidden=state.stage===0;
    document.getElementById("nextStage").hidden=state.stage===4;
    document.getElementById("submitSubmission").hidden=state.stage!==4;
    document.getElementById("validationSummary").innerHTML="";
    var legend=document.querySelector('[data-stage="'+state.stage+'"] legend');if(legend)legend.focus&&legend.focus();
  }
  function syncDateKind(){var kind=val("dateKind"),timed=kind==="timed";["startsAt","endsAt"].forEach(function(id){var input=document.getElementById(id);input.type=timed?"datetime-local":"date";input.value=input.value.slice(0,timed?16:10);});document.getElementById("doorsAt").closest("label").hidden=!timed;document.getElementById("startsLabel").textContent=kind==="date_range"?"First date *":kind==="all_day"?"Event date *":"Starts *";document.getElementById("endsLabel").textContent=kind==="date_range"?"Last date *":"Ends";}
  function syncOnline(){var online=document.getElementById("online").checked;["venueName","venueUrl","venueAddress"].forEach(function(id){document.getElementById(id).disabled=online;});}
  function addPerson(person){var row=document.createElement("div");row.className="repeater-row";row.dataset.person="";row.innerHTML='<label><span>Name</span><input data-person-name value="'+esc(person.name)+'"></label><label><span>Type</span><select data-person-role><option value="artist">Artist</option><option value="participant">Participant</option><option value="organizer">Organizer</option><option value="venue">Venue</option><option value="supporting">Related</option></select></label><label><span>URL + role credit</span><input data-person-url type="url" value="'+esc(person.url)+'" placeholder="https://…"><input data-person-credit value="'+esc(person.creditRole)+'" placeholder="Poet, performer, curator…"></label><button class="compact-button is-danger" data-remove-row type="button">Remove</button>';row.querySelector("select").value=person.role||"participant";document.getElementById("peopleRows").appendChild(row);}
  function addOccurrence(item){var row=document.createElement("div");row.className="repeater-row occurrence-row";row.dataset.occurrence="";row.innerHTML='<label><span>Program title</span><input data-occurrence-title value="'+esc(item.title)+'"></label><label><span>Starts</span><input data-occurrence-starts type="datetime-local" value="'+esc(controlDate(item.startsAt))+'"></label><label><span>Venue / source</span><input data-occurrence-venue value="'+esc(item.venueName)+'" placeholder="Venue"><input data-occurrence-source type="url" value="'+esc(item.sourceUrl)+'" placeholder="https://…"></label><button class="compact-button is-danger" data-remove-row type="button">Remove</button>';document.getElementById("occurrenceRows").appendChild(row);}
  function removeRow(event){var button=event.target.closest("[data-remove-row]");if(button)button.closest(".repeater-row").remove();}
  function stageFiles(event){var incoming=Array.from(event.target.files||[]);var total=state.files.reduce(function(sum,item){return sum+item.file.size;},0);var errors=[];incoming.forEach(function(file){if(state.files.length>=6)return errors.push("No more than 6 images may be staged.");if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))return errors.push(file.name+" is not a supported image.");if(file.size>15*1024*1024)return errors.push(file.name+" is larger than 15 MB.");if(total+file.size>45*1024*1024)return errors.push("Staged images may total no more than 45 MB.");state.files.push({id:crypto.randomUUID(),file:file,url:URL.createObjectURL(file)});total+=file.size;});event.target.value="";renderFiles();if(errors.length)showErrors(errors);}
  function renderFiles(){var root=document.getElementById("stagedFiles");root.innerHTML=state.media.concat(state.files).map(function(item,index){var existing=Boolean(item.mediaId);return '<article class="staged-file" data-file-id="'+esc(item.id)+'" data-existing="'+existing+'"><img src="'+esc(item.previewUrl||item.url)+'" alt=""><div><strong>'+esc(item.originalFilename||item.file.name)+'</strong><p class="submission-help">'+Math.round((item.byteSize||item.file.size)/1024)+' KB / position '+(index+1)+'</p></div><div class="staged-file-actions"><button class="compact-button" data-file-up type="button" aria-label="Move image earlier">Up</button><button class="compact-button" data-file-down type="button" aria-label="Move image later">Down</button><button class="compact-button is-danger" data-file-remove type="button">Remove</button></div></article>';}).join("");document.getElementById("fileCount").textContent=(state.media.length+state.files.length)+" of 6 images staged. JPEG, PNG, WebP, or GIF; 15 MB each, 45 MB total.";}
  function fileAction(event){var card=event.target.closest("[data-file-id]");if(!card)return;var list=card.dataset.existing==="true"?state.media:state.files;var index=list.findIndex(function(item){return item.id===card.dataset.fileId;});if(index<0)return;if(event.target.closest("[data-file-remove]")){var removed=list.splice(index,1)[0];if(removed.url)URL.revokeObjectURL(removed.url);}else if(event.target.closest("[data-file-up]")&&index>0){list.splice(index-1,0,list.splice(index,1)[0]);}else if(event.target.closest("[data-file-down]")&&index<list.length-1){list.splice(index+1,0,list.splice(index,1)[0]);}renderFiles();}
  function timeZoneOffset(localValue,timeZone){var match=String(localValue||"").match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!match)return "";var guess=Date.UTC(+match[1],+match[2]-1,+match[3],+match[4],+match[5]);function offsetAt(timestamp){var parts=new Intl.DateTimeFormat("en-US",{timeZone:timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(timestamp)).reduce(function(values,part){values[part.type]=part.value;return values;},{});return Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second)-timestamp;}var offset=offsetAt(guess);offset=offsetAt(guess-offset);var sign=offset>=0?"+":"-",minutes=Math.abs(Math.round(offset/60000));return sign+String(Math.floor(minutes/60)).padStart(2,"0")+":"+String(minutes%60).padStart(2,"0");}
  function payloadDate(value,kind){if(!value)return "";if(kind!=="timed")return value.slice(0,10);return value+":00"+timeZoneOffset(value,"America/New_York");}
  function controlDate(value){return String(value||"").slice(0,16);}
  function payload(){var kind=checked("kind")[0]||"new",dateKind=val("dateKind");return {kind:kind,targetUrl:val("targetUrl"),correctionSummary:val("correctionSummary"),title:val("eventTitle"),factualDescription:val("description"),eventStructure:val("eventStructure"),dateKind:dateKind,startsAt:payloadDate(val("startsAt"),dateKind),endsAt:payloadDate(val("endsAt"),dateKind),doorsAt:payloadDate(val("doorsAt"),"timed"),timezone:"America/New_York",organizer:val("organizer"),organizerUrl:val("organizerUrl"),venueName:val("venueName"),venueAddress:val("venueAddress"),venueUrl:val("venueUrl"),online:document.getElementById("online").checked,city:val("city"),region:val("region"),atlantaMetroConfirmed:document.getElementById("atlantaConfirmed").checked,sourceUrl:val("sourceUrl"),discoveryUrl:val("discoveryUrl"),ticketUrl:val("ticketUrl"),admissionType:val("admissionType"),admissionNotes:val("admissionNotes"),accessNotes:val("accessNotes"),ageNotes:val("ageNotes"),accessibilityNotes:val("accessibilityNotes"),subjects:checked("subjects"),formats:checked("formats"),experimental:document.getElementById("experimental").checked,people:Array.from(document.querySelectorAll("[data-person]")).map(function(row){return {name:row.querySelector("[data-person-name]").value.trim(),role:row.querySelector("[data-person-role]").value,url:row.querySelector("[data-person-url]").value.trim(),creditRole:row.querySelector("[data-person-credit]").value.trim()};}).filter(function(item){return item.name;}),occurrences:Array.from(document.querySelectorAll("[data-occurrence]")).map(function(row){var starts=row.querySelector("[data-occurrence-starts]").value;return {title:row.querySelector("[data-occurrence-title]").value.trim(),occurrenceType:"other",dateKind:"timed",startsAt:payloadDate(starts,"timed"),endsAt:"",timezone:"America/New_York",venueName:row.querySelector("[data-occurrence-venue]").value.trim(),sourceUrl:row.querySelector("[data-occurrence-source]").value.trim()};}).filter(function(item){return item.title||item.startsAt;}),submitterName:val("submitterName"),submitterEmail:val("submitterEmail"),submitterPhone:val("submitterPhone"),submitterRelationship:val("submitterRelationship"),rightsConfirmed:document.getElementById("rightsConfirmed").checked,editorialConfirmed:document.getElementById("editorialConfirmed").checked,media:state.media.map(function(item,index){return {id:item.id,altText:item.altText,caption:item.caption,sortOrder:index};})};}
  function stageErrors(stage){var data=payload(),errors=[];if(stage===0){if(!data.title)errors.push("Enter the event title.");if(!data.factualDescription)errors.push("Enter a factual description.");if(!data.subjects.length&&!data.formats.length)errors.push("Choose at least one creative subject or format.");if(data.kind==="correction"&&(!data.targetUrl||!data.correctionSummary))errors.push("Add the current listing URL and explain the correction.");}if(stage===1){if(!data.startsAt)errors.push("Choose the event start date.");if(data.dateKind==="date_range"&&!data.endsAt)errors.push("Choose the final date.");if(!data.online&&!data.venueName)errors.push("Enter a venue or choose online event.");if(!data.atlantaMetroConfirmed)errors.push("Confirm the Atlanta metro location.");}if(stage===2&&!data.organizer)errors.push("Enter the primary organizer.");if(stage===3){if(!data.admissionType)errors.push("Choose the admission type.");if(!data.sourceUrl&&!data.ticketUrl&&state.files.length+state.media.length===0)errors.push("Add an official link, ticket or RSVP link, or flyer.");}if(stage===4){if(!data.submitterName)errors.push("Enter your name.");if(!/^\S+@\S+\.\S+$/.test(data.submitterEmail))errors.push("Enter a valid email.");if(!data.rightsConfirmed||!data.editorialConfirmed)errors.push("Confirm both consent statements.");}return errors;}
  function showErrors(errors){var root=document.getElementById("validationSummary");root.innerHTML='<strong>Please check this step.</strong><ul>'+errors.map(function(error){return '<li>'+esc(error)+'</li>';}).join("")+'</ul>';root.focus();}
  async function submit(event){event.preventDefault();var errors=stageErrors(4);if(errors.length)return showErrors(errors);var button=document.getElementById("submitSubmission");button.disabled=true;button.textContent=mode==="manage"?"Saving…":"Sending…";var form=new FormData();form.set("payload",JSON.stringify(payload()));form.set("website",val("website"));state.files.forEach(function(item){form.append("flyers",item.file,item.file.name);});if(mode==="create"){var responseToken=document.querySelector('[name="cf-turnstile-response"]');form.set("cf-turnstile-response",responseToken?responseToken.value:"");}try{var response=await fetch(mode==="manage"?"/api/calendar/submissions/manage":"/api/calendar/submissions",{method:mode==="manage"?"PATCH":"POST",headers:mode==="manage"?{authorization:"Bearer "+state.token}:{"Idempotency-Key":state.idempotencyKey},body:form});var result=await response.json().catch(function(){return {};});if(!response.ok)throw Object.assign(new Error(result.error||"Submission failed."),{errors:result.errors||[]});if(mode==="manage"){state.submission=result.submission;state.files.forEach(function(item){URL.revokeObjectURL(item.url);});state.files=[];await showManaged(result.submission,true);}else{app.innerHTML='<section class="submission-result"><span class="status-pill">Received</span><h3>Thank you.</h3><p>Your reference is <strong>'+esc(result.reference)+'</strong>. Nothing has been published; Studio review is private.</p><p>A receipt with the private management link has been sent when email delivery is available.</p><p><a href="'+esc(result.manageUrl)+'">Open the private management page</a></p></section>';}}catch(error){showErrors([error.message].concat(error.errors||[]));if(mode==="create"&&window.turnstile&&state.turnstileId!==null)window.turnstile.reset(state.turnstileId);}finally{if(document.body.contains(button)){button.disabled=false;button.textContent=mode==="manage"?"Save changes":"Send for private review";}}}
  async function setupTurnstile(){try{var response=await fetch("/api/calendar/submissions/config",{headers:{accept:"application/json"}}),config=await response.json();if(!response.ok||!config.configured)throw new Error("Verification is not configured.");function render(){if(!window.turnstile)return setTimeout(render,80);state.turnstileId=window.turnstile.render("#turnstileWrap",{sitekey:config.siteKey,action:config.action,theme:"dark"});}render();}catch(error){document.getElementById("turnstileWrap").innerHTML='<p class="submission-help">'+esc(error.message)+' Submissions fail closed until Studio completes the private verification setup.</p>';}}
  function setValue(id,value){var field=document.getElementById(id);if(field)field.value=value==null?"":value;}
  function populate(submission){var data=submission.payload||{};Object.keys({targetUrl:1,correctionSummary:1,eventTitle:1,description:1,eventStructure:1,dateKind:1,timezone:1,startsAt:1,endsAt:1,doorsAt:1,organizer:1,organizerUrl:1,venueName:1,venueAddress:1,venueUrl:1,city:1,region:1,sourceUrl:1,discoveryUrl:1,ticketUrl:1,admissionType:1,admissionNotes:1,accessNotes:1,ageNotes:1,accessibilityNotes:1,submitterName:1,submitterEmail:1,submitterPhone:1,submitterRelationship:1}).forEach(function(id){var key={eventTitle:"title",description:"factualDescription"}[id]||id;var value=data[key];if(["startsAt","endsAt","doorsAt"].includes(id))value=controlDate(value);if(id.startsWith("submitter"))value=(submission.submitter||{})[id.replace("submitter","").replace(/^./,function(c){return c.toLowerCase();})];setValue(id,value);});document.querySelectorAll('input[name="kind"]').forEach(function(input){input.checked=input.value===submission.kind;});document.querySelectorAll('input[name="subjects"],input[name="formats"]').forEach(function(input){input.checked=(data[input.name]||[]).includes(input.value);});["experimental","online","atlantaConfirmed","rightsConfirmed","editorialConfirmed"].forEach(function(id){var key={atlantaConfirmed:"atlantaMetroConfirmed"}[id]||id;document.getElementById(id).checked=Boolean(data[key]);});document.querySelectorAll(".correction-only").forEach(function(item){item.hidden=submission.kind!=="correction";});(data.people||[]).forEach(addPerson);(data.occurrences||[]).forEach(addOccurrence);syncDateKind();syncOnline();}
  function statusLabel(status){return ({received:"Received",needs_information:"Needs information",converted:"In Studio verification",added:"Added to calendar",duplicate:"Closed as duplicate",declined:"Declined",withdrawn:"Withdrawn"})[status]||status.replace(/_/g," ");}
  async function mediaPreview(item){try{var response=await fetch("/api/calendar/submissions/manage/media/"+encodeURIComponent(item.id),{headers:{authorization:"Bearer "+state.token}});if(!response.ok)return item;var blob=await response.blob();item.previewUrl=URL.createObjectURL(blob);}catch(error){}return item;}
  async function showManaged(submission,saved){state.submission=submission;shell();populate(submission);state.media=await Promise.all((submission.media||[]).map(mediaPreview));renderFiles();var status=document.getElementById("manageStatus");status.innerHTML='<div><span class="status-pill">'+esc(statusLabel(submission.status))+'</span><h3>'+esc(submission.reference)+'</h3><p>'+esc(submission.payload.title)+'</p>'+(saved?'<p role="status">Your changes were saved as a new private revision.</p>':'')+'</div>'+(submission.editable?'<button class="compact-button withdraw-button" data-withdraw type="button">Withdraw submission</button>':'');var form=document.getElementById("calendarSubmissionForm");if(!submission.editable){form.classList.add("is-readonly");form.querySelectorAll("input,select,textarea,button").forEach(function(control){control.disabled=true;});document.querySelector(".submission-actions").hidden=true;}}
  async function withdraw(){if(!window.confirm("Withdraw this submission? It will become read-only."))return;var response=await fetch("/api/calendar/submissions/manage",{method:"DELETE",headers:{authorization:"Bearer "+state.token}}),result=await response.json().catch(function(){return {};});if(!response.ok)return showErrors([result.error||"Withdrawal failed."]);state.submission.status=result.status;state.submission.editable=false;showManaged(state.submission,false);}
  async function loadManaged(){var params=new URLSearchParams(location.hash.replace(/^#/,""));state.token=params.get("token")||"";if(!state.token){app.innerHTML='<section class="submission-result"><h3>Private link missing.</h3><p>Open the complete management link from your receipt email.</p></section>';return;}history.replaceState(null,"",location.pathname+location.hash);try{var response=await fetch("/api/calendar/submissions/manage",{headers:{authorization:"Bearer "+state.token}}),result=await response.json().catch(function(){return {};});if(!response.ok)throw new Error(result.error||"The private link could not be opened.");showManaged(result.submission,false);}catch(error){app.innerHTML='<section class="submission-result"><h3>Link unavailable.</h3><p>'+esc(error.message)+'</p></section>';}}
  if(mode==="manage")loadManaged();else{shell();setupTurnstile();}
})();
