(function(){
  const previewBanner=document.querySelector(".preview-banner");if(previewBanner)previewBanner.textContent="QA mirror · noindex · reads the same live managed API as the public surface";
  const root=document.querySelector("[data-managed-catalog]");if(!root)return;
  const readOnlyPreview=location.pathname.includes("managed-preview");
  const type=root.dataset.managedCatalog;const endpoint={flash:"/api/flash",legend:"/api/legend","visual-language":"/api/visual-language","legend-categories":"/api/legend/categories",art:"/api/art",archive:"/api/archive","archive-collections":"/api/archive-collections",navigation:"/api/site/navigation",search:"/api/search"}[type];
  let records=[],lastFocus=null;const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const media=r=>r.media?.[0];const title=r=>r.title||r.name||r.slug||r.id;const meta=r=>[r.state,r.series_id,r.category_id,r.year,r.medium,r.room,r.node_label].filter(Boolean).join(" · ");
  function card(r){const m=media(r);if(type==="legend"||type==="visual-language")return `<button class="card" type="button" data-id="${esc(r.id)}"${document.querySelector("[data-symbol-form]")?' aria-pressed="false"':""}><span class="symbol-mark" aria-hidden="true">${r.svg_markup||""}</span><span class="card-copy"><h2>${esc(title(r))}</h2><span class="meta">${esc(r.category_id)}</span><p>${esc(r.meaning)}</p></span></button>`;if(type==="navigation")return `<article class="card node"><div class="card-copy"><h2>${esc(r.name)}</h2><span class="meta">${r.pathways?.length||0} pathways</span><div class="pathways">${(r.pathways||[]).map(p=>`<a href="${esc(p.route)}">${esc(p.name)}</a>`).join("")}</div></div></article>`;if(type==="legend-categories"||type==="archive-collections")return `<article class="card"><span class="card-copy"><h2>${esc(title(r))}</h2><span class="meta">${esc(meta(r))}</span><p>${esc(r.description||"")}</p></span></article>`;return `<button class="card" type="button" data-id="${esc(r.id)}">${m?`<img src="${esc(m.url)}" alt="${esc(m.alt||title(r))}" loading="lazy">`:""}<span class="card-copy"><h2>${esc(title(r))}</h2><span class="meta">${esc(meta(r))}</span><p>${esc(r.description||r.summary||r.statement||r.meaning||"")}</p></span></button>`}
  function paint(list=records){root.innerHTML=list.length?list.map(card).join(""):`<div class="empty">No published records match this view.</div>`}
  function open(r,button,historyMode="push"){const dialog=document.getElementById("managed-detail");if(!dialog)return;lastFocus=button;dialog.querySelector("[data-dialog-content]").innerHTML=`${media(r)?`<img src="${esc(media(r).url)}" alt="${esc(media(r).alt||title(r))}">`:(type==="legend"||type==="visual-language")?`<div class="symbol-mark" aria-hidden="true">${r.svg_markup||""}</div>`:""}<h2 id="managed-dialog-title">${esc(title(r))}</h2><p class="meta">${esc(meta(r))}</p><p>${esc(r.description||r.summary||r.statement||r.meaning||r.body||"")}</p><div data-dialog-connections></div>`;dialog.showModal();dialog.querySelector("[data-close]").focus();if(historyMode==="push"){const url=new URL(location.href);url.searchParams.set(type==="archive"?"record":"entity",r.slug||r.id);history.pushState({managedEntity:r.id},"",url)}const mount=()=>window.ConstructConnections?.mount({entityId:r.id,host:dialog.querySelector("[data-dialog-connections]")});if(window.ConstructConnections)mount();else{const script=document.createElement("script");script.src="/js/construct-connections.js?v=5";script.onload=mount;document.head.appendChild(script)}}
  root.addEventListener("click",e=>{const b=e.target.closest("[data-id]");if(!b)return;const r=records.find(x=>x.id===b.dataset.id);if((type==="legend"||type==="visual-language")&&document.querySelector("[data-symbol-form]")){b.setAttribute("aria-pressed",b.getAttribute("aria-pressed")!=="true");updateSymbolField();return}if(r)open(r,b)});
  const dialog=document.getElementById("managed-detail");dialog?.addEventListener("click",e=>{if(e.target===dialog||e.target.closest("[data-close]")){const key=type==="archive"?"record":"entity";if(new URL(location.href).searchParams.has(key))history.back();else dialog.close()}});dialog?.addEventListener("close",()=>lastFocus?.focus());window.addEventListener("popstate",()=>{const key=type==="archive"?"record":"entity",selected=new URL(location.href).searchParams.get(key),record=records.find(item=>(item.slug||item.id)===selected);if(record)open(record,null,"none");else if(dialog?.open)dialog.close()});
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&dialog?.open){e.preventDefault();dialog.close()}});
  function updateSymbolField(){const input=document.querySelector("[name=symbol_ids]");if(input)input.value=[...root.querySelectorAll('[aria-pressed="true"]')].map(b=>b.dataset.id).join(",")}
  document.querySelector("[data-symbol-form]")?.addEventListener("submit",async e=>{e.preventDefault();if(!e.target.reportValidity())return;const status=e.target.querySelector("[data-form-status]");if(readOnlyPreview){status.textContent="Preview is read-only. No brief was submitted.";return}const form=new FormData(e.target);const ids=[...new Set(String(form.get("symbol_ids")||"").split(",").filter(Boolean))];if(!ids.length){status.textContent="Choose at least one symbol.";return}if(ids.length>12){status.textContent="Choose no more than 12 symbols.";return}const payload={type:"build_brief",name:form.get("name"),email:form.get("email"),placement:form.get("placement"),dob:form.get("dob"),selected_elements:ids.join(", "),symbol_ids:ids,age_confirmed:form.get("age_confirmed"),review_consent:"yes",source_path:location.pathname};const response=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();status.textContent=response.ok?"Brief received.":result.error||"Unable to submit."});
  document.querySelector("[data-search-form]")?.addEventListener("submit",e=>{e.preventDefault();load(new URLSearchParams(new FormData(e.target)).toString())});
  async function load(query=""){root.innerHTML=`<div class="empty">Loading managed records…</div>`;try{const response=await fetch(`${endpoint}${query?`?${query}`:""}`,{headers:{accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error();const payload=await response.json();records=type==="navigation"?(payload.nodes||[]):(payload.records||[]);paint();const key=type==="archive"?"record":"entity",selected=new URL(location.href).searchParams.get(key),record=records.find(item=>(item.slug||item.id)===selected);if(record)open(record,null,"none")}catch{root.innerHTML=`<div class="empty" role="alert">This catalog is temporarily unavailable. <a href="/tattoos/inquire/">Send an inquiry</a>.</div>`}}
  load();
})();
