import assert from "node:assert/strict";
import { readFileSync,readdirSync } from "node:fs";
import { dirname,join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { handleConstructApi } from "../functions/api/construct/_lib.js";

const ROOT=dirname(dirname(fileURLToPath(import.meta.url))),TOKEN="archive-note-test";
class Statement{constructor(database,sql,values=[]){this.database=database;this.sql=sql;this.values=values}bind(...values){return new Statement(this.database,this.sql,values)}async first(){return this.database.prepare(this.sql).get(...this.values)||null}async all(){return{results:this.database.prepare(this.sql).all(...this.values)}}async run(){const statement=this.database.prepare(this.sql);if(statement.sourceSQL.trimStart().toUpperCase().startsWith("SELECT"))return{results:statement.all(...this.values)};const result=statement.run(...this.values);return{success:true,meta:{changes:Number(result.changes||0)}}}}
class LocalD1{constructor(database){this.database=database}prepare(sql){return new Statement(this.database,sql)}async batch(statements){this.database.exec("BEGIN");try{const results=[];for(const statement of statements)results.push(await statement.run());this.database.exec("COMMIT");return results}catch(error){this.database.exec("ROLLBACK");throw error}}}
function database(){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const name of readdirSync(join(ROOT,"migrations")).filter(value=>value.endsWith(".sql")).sort())db.exec(readFileSync(join(ROOT,"migrations",name),"utf8"));return db}
function env(db){return{SUBMISSIONS_DB:new LocalD1(db),SUBMISSIONS_ADMIN_TOKEN:TOKEN}}
function request(path,{method="GET",body,admin=false}={}){return new Request(`https://example.test${path}`,{method,headers:{...(body===undefined?{}:{"content-type":"application/json"}),...(admin?{authorization:`Bearer ${TOKEN}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})})}
async function json(response){return{status:response.status,body:await response.json()}}
function insertMedia(db,{id,mime="image/png",privacy="public",presentation="inline",alt="",caption=""}){db.prepare(`INSERT INTO media_assets(id,source_url,original_filename,mime_type,byte_size,alt_text,caption,privacy,state,created_by,created_at,updated_at,public_presentation) VALUES(?,?,?,?,1,?,?,?,'active','test',datetime('now'),datetime('now'),?)`).run(id,`/assets/${id}`,`${id}.${mime==="application/pdf"?"pdf":"png"}`,mime,alt,caption,privacy,presentation)}

test("Lost Marbles Note is one public identity across Notes, Notebook, Origin Thread, and search",async()=>{
  const db=database(),runtime=env(db);
  const body=`{{asset:original-sketch}}\n\nWanting to lose certain marbles purposely wanting some screws loose. Having some embedded in the body , based off the book the body keeps score with trauma, so I can replace, put the marbles back when healing/when I need to heal.\n\nSome of them I hid in the subconscious pit\n\nAdd a drain instead of a pit and add some water around it being drained\n\n{{asset:process-experiment}}`;
  const created=await json(await handleConstructApi(request("/api/admin/archive-notes",{method:"POST",admin:true,body:{title:"Lost Marbles Inception Note",slug:"lost-marbles-inception-note",note_type:"concept-note",source_app:"Apple Notes",body_markdown:body,excerpt:"The original sketch and written inception of Lost Marbles.",source_created_at:"2022-12-23T19:54:00-05:00",source_modified_at:"2023-11-26",date_label:"Created December 23, 2022 at 7:54 PM · Last edited November 26, 2023",provenance_note:"Archived as Markdown and reconstructed here to preserve the sequence, rhythm, and appearance of the original Apple Notes entry as it appeared on my iPhone.",state:"draft",public_visible:false,links:[{target_entity_id:"art-marbles",relationship_role:"inception",is_primary:true,public_visible:true}],origin_thread_ids:["origin-thread-lost-marbles"],primary_origin_thread_id:"origin-thread-lost-marbles"}}),runtime));
  assert.equal(created.status,201,created.body.error);const noteId=created.body.note.id;
  insertMedia(db,{id:"note-sketch",alt:"Original handwritten sketch",caption:"Original handwritten sketch from the Lost Marbles inception note."});
  insertMedia(db,{id:"note-process",alt:"Process experiment drawn over a photograph",caption:"Process experiment"});
  insertMedia(db,{id:"note-source-pdf",mime:"application/pdf",privacy:"internal",presentation:"hidden",alt:"Apple Notes source PDF"});
  const assets=[
    {media_id:"note-sketch",asset_token:"original-sketch",role:"inline-image",sort_order:1,alt_text:"Original handwritten sketch",caption:"Original handwritten sketch from the Lost Marbles inception note.",public_visible:true},
    {media_id:"note-process",asset_token:"process-experiment",role:"inline-image",sort_order:2,alt_text:"A process experiment drawn over a photograph of the painting",caption:"Process experiment added to this note later. I drew over a photograph of the painting to test an idea. I did not use it for this painting, but kept it as a possible reference for another work.",public_visible:true},
    {media_id:"note-source-pdf",asset_token:"apple-notes-source",role:"source-provenance",sort_order:3,alt_text:"Apple Notes source PDF",caption:"Private source provenance",public_visible:false},
  ];
  for(const asset of assets){const response=await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/assets`,{method:"POST",admin:true,body:asset}),runtime);assert.equal(response.status,201,JSON.stringify(await response.json()))}
  const published=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}`,{method:"PATCH",admin:true,body:{state:"published",public_visible:true,links:[{target_entity_id:"art-marbles",relationship_role:"inception",is_primary:true,public_visible:true}],origin_thread_ids:["origin-thread-lost-marbles"],primary_origin_thread_id:"origin-thread-lost-marbles"}}),runtime));
  assert.equal(published.status,200,published.body.error);
  assert.deepEqual({...db.prepare("SELECT state,public_visible FROM archive_notes WHERE entity_id=?").get(noteId)},{state:"published",public_visible:1});
  assert.deepEqual({...db.prepare("SELECT visibility,search_visibility FROM content_entities WHERE id=?").get(noteId)},{visibility:"public",search_visibility:1});
  assert.deepEqual({...db.prepare("SELECT relationship_role,is_primary,public_visible FROM archive_note_links WHERE note_entity_id=? AND target_entity_id='art-marbles'").get(noteId)},{relationship_role:"inception",is_primary:1,public_visible:1});
  assert.deepEqual(db.prepare("SELECT id,privacy,state,public_presentation FROM media_assets WHERE id IN ('note-sketch','note-process','note-source-pdf') ORDER BY id").all().map(row=>({...row})),[
    {id:"note-process",privacy:"public",state:"active",public_presentation:"inline"},
    {id:"note-sketch",privacy:"public",state:"active",public_presentation:"inline"},
    {id:"note-source-pdf",privacy:"internal",state:"active",public_presentation:"hidden"},
  ]);

  const index=await json(await handleConstructApi(request("/api/archive/notes"),runtime));assert.equal(index.status,200);assert.deepEqual(index.body.records.map(note=>note.slug),["lost-marbles-inception-note"]);
  const detail=await json(await handleConstructApi(request("/api/archive/notes/lost-marbles-inception-note"),runtime));assert.equal(detail.status,200);assert.equal(detail.body.note.source_created_at,"2022-12-23T19:54:00-05:00");assert.equal(detail.body.note.provenance_note,"Archived as Markdown and reconstructed here to preserve the sequence, rhythm, and appearance of the original Apple Notes entry as it appeared on my iPhone.");assert.equal(detail.body.assets.length,2);assert.deepEqual(detail.body.assets.map(asset=>asset.token),["original-sketch","process-experiment"]);assert.equal(JSON.stringify(detail.body).includes("note-source-pdf"),false);assert.match(detail.body.assets[1].caption,/possible reference for another work/);
  const dossier=await json(await handleConstructApi(request("/api/archive/items/lostmarbles"),runtime));assert.equal(dossier.status,200);assert.deepEqual(dossier.body.notes.map(note=>note.id),[noteId]);assert.deepEqual(dossier.body.notes[0].assets.map(asset=>asset.token),["original-sketch","process-experiment"]);
  const origin=await json(await handleConstructApi(request("/api/archive/items?origin=lost-marbles&limit=100"),runtime));assert.equal(origin.status,200);assert.deepEqual(origin.body.notes.map(note=>note.id),[noteId]);
  const search=await json(await handleConstructApi(request("/api/search?q=subconscious%20pit"),runtime));assert.ok(search.body.records.some(record=>record.entity_id===noteId&&record.route==="/archive/notes/lost-marbles-inception-note/"));
  const searchDocument=db.prepare("SELECT * FROM search_documents WHERE entity_id=?").get(noteId);assert.equal(searchDocument.entity_type,"archive_note");assert.match(searchDocument.body,/possible reference for another work/);assert.match(searchDocument.body,/reconstructed here/);

  db.prepare("INSERT INTO content_entities(id,entity_type,node_id,visibility,search_visibility,created_by,updated_by,created_at,updated_at) VALUES('related-note-test','archive_record','archive','public',1,'test','test',datetime('now'),datetime('now'))").run();
  const linked=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/links`,{method:"PUT",admin:true,body:{links:[{target_entity_id:"art-marbles",relationship_role:"inception",is_primary:true,public_visible:true},{target_entity_id:"related-note-test",relationship_role:"reference",public_visible:true}]}}),runtime));assert.equal(linked.status,200);assert.equal(linked.body.records.length,2);
  const linkIndex=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/links`,{admin:true}),runtime));assert.deepEqual(linkIndex.body.records.map(link=>link.relationship_role),["inception","reference"]);

  const exported=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/export`,{admin:true}),runtime));assert.equal(exported.status,200);assert.equal(exported.body.filename,"lost-marbles-inception-note.zip");assert.deepEqual(exported.body.attachments.map(asset=>asset.token),["original-sketch","process-experiment"]);assert.match(exported.body.markdown,/Attachments\/note-sketch\.png/);assert.match(exported.body.markdown,/Attachments\/note-process\.png/);assert.doesNotMatch(JSON.stringify(exported.body),/note-source-pdf|apple-notes-source|Private source provenance/);
  const imported=await json(await handleConstructApi(request("/api/admin/archive-notes/import",{method:"POST",admin:true,body:{title:"Round Trip Note",slug:"round-trip-note",filename:exported.body.markdown_filename,markdown:exported.body.markdown,attachments:exported.body.attachments.map(asset=>({name:asset.filename,mime_type:asset.mime_type}))}}),runtime));assert.equal(imported.status,201,imported.body.error);assert.equal(imported.body.note.state,"draft");assert.equal(imported.body.note.body_markdown.replace(/\{\{asset:[^}]+\}\}/g,"{{asset}}"),body.replace(/\{\{asset:[^}]+\}\}/g,"{{asset}}"));assert.deepEqual(imported.body.import_plan.attachments.map(asset=>[asset.token,asset.role,asset.public_visible]),[["note-sketch","inline-image",true],["note-process","inline-image",true]]);assert.equal(imported.body.links.length,2);
  const importedMedia=new Map([["note-sketch","note-sketch"],["note-process","note-process"]]);for(const asset of imported.body.import_plan.attachments){const attached=await json(await handleConstructApi(request(`/api/admin/archive-notes/${imported.body.note.id}/assets`,{method:"POST",admin:true,body:{media_id:importedMedia.get(asset.token),asset_token:asset.token,role:asset.role,sort_order:asset.sort_order,alt_text:asset.alt_text,public_visible:asset.public_visible}}),runtime));assert.equal(attached.status,201,attached.body.error)}
  const reexported=await json(await handleConstructApi(request(`/api/admin/archive-notes/${imported.body.note.id}/export`,{admin:true}),runtime));assert.deepEqual(reexported.body.attachments.map(asset=>asset.filename),exported.body.attachments.map(asset=>asset.filename));assert.doesNotMatch(JSON.stringify(reexported.body),/source-provenance|note-source-pdf/);

  const guarded=await json(await handleConstructApi(request("/api/admin/media/note-process",{method:"PATCH",admin:true,body:{privacy:"internal"}}),runtime));assert.equal(guarded.status,409);assert.match(guarded.body.error,/Unpublish the Archive Note/);
});

test("public Notes reject unsafe Markdown and unresolved managed assets",async()=>{
  const db=database(),runtime=env(db);
  assert.equal((await handleConstructApi(request("/api/admin/archive-notes/import",{method:"POST",body:{filename:"private.md",markdown:"Private"}}),runtime)).status,401);
  const unsafe=await json(await handleConstructApi(request("/api/admin/archive-notes",{method:"POST",admin:true,body:{title:"Unsafe",slug:"unsafe",body_markdown:'<script>alert(1)</script> ![x](https://example.test/x.jpg)',state:"published",public_visible:true}}),runtime));assert.equal(unsafe.status,400);assert.match(unsafe.body.error,/executable|external image/i);
  const missing=await json(await handleConstructApi(request("/api/admin/archive-notes",{method:"POST",admin:true,body:{title:"Missing",slug:"missing",body_markdown:"{{asset:not-there}}",state:"published",public_visible:true}}),runtime));assert.equal(missing.status,400);assert.match(missing.body.error,/missing asset token/i);
});

test("Journal-derived history stays private until approval and requires explicit replacement",async()=>{
  const db=database(),runtime=env(db);
  const created=await json(await handleConstructApi(request("/api/admin/archive-notes",{method:"POST",admin:true,body:{title:"A studio turning point",slug:"studio-turning-point",note_type:"journal-entry",source_app:"Studio",body_markdown:"I removed the central form and the work finally opened up.",excerpt:"A decisive removal changed the work.",source_created_at:"2026-08-20T14:30:00-04:00",date_label:"August 20, 2026",state:"draft",public_visible:false,links:[{target_entity_id:"art-marbles",relationship_role:"development",is_primary:true,public_visible:false}]}}),runtime));
  assert.equal(created.status,201,created.body.error);const noteId=created.body.note.id;
  const suggested=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions`,{method:"POST",admin:true,body:{target_entity_id:"art-marbles"}}),runtime));
  assert.equal(suggested.status,201,suggested.body.error);const suggestionId=suggested.body.record.id;assert.equal(suggested.body.record.status,"pending");assert.equal(suggested.body.record.activity_id,null);
  assert.equal(db.prepare("SELECT COUNT(*) count FROM entity_activity WHERE entity_id='art-marbles' AND title='A studio turning point'").get().count,0);

  const rejected=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"reject"}}),runtime));assert.equal(rejected.status,200,rejected.body.error);assert.equal(rejected.body.record.status,"rejected");
  const resaved=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"save",title:"Central form removed",summary:"Removing the central form opened the composition."}}),runtime));assert.equal(resaved.status,200,resaved.body.error);assert.equal(resaved.body.record.status,"pending");
  db.prepare("UPDATE archive_dossiers SET state='draft',public_visible=0 WHERE entity_id='art-marbles'").run();
  const blockedPublic=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"approve",title:"Central form removed",summary:"Removing the central form opened the composition.",public_visible:true}}),runtime));assert.equal(blockedPublic.status,409);assert.match(blockedPublic.body.error,/Publish the canonical entity and dossier/);assert.equal(db.prepare("SELECT COUNT(*) count FROM entity_activity WHERE entity_id='art-marbles' AND title='Central form removed'").get().count,0);
  db.prepare("UPDATE archive_dossiers SET state='published',public_visible=1 WHERE entity_id='art-marbles'").run();

  const approved=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"approve",activity_type:"revision",title:"Central form removed",summary:"Removing the central form opened the composition.",body:"Approved factual account.",occurred_at:"2026-08-20",date_precision:"exact",date_label:"August 20, 2026",public_visible:false}}),runtime));
  assert.equal(approved.status,200,approved.body.error);const activityId=approved.body.activity.id;assert.equal(approved.body.record.status,"approved");assert.equal(db.prepare("SELECT title FROM entity_activity WHERE id=?").get(activityId).title,"Central form removed");
  assert.equal(db.prepare("SELECT COUNT(*) count FROM entity_revisions WHERE entity_id='art-marbles' AND action='archive-note-history-approve'").get().count,1);

  const manual=await json(await handleConstructApi(request(`/api/admin/archive-activities/${activityId}`,{method:"PATCH",admin:true,body:{title:"Studio-authoritative title"}}),runtime));assert.equal(manual.status,200,manual.body.error);
  await handleConstructApi(request(`/api/admin/archive-notes/${noteId}`,{method:"PATCH",admin:true,body:{body_markdown:"The Journal account changed after approved history was written."}}),runtime);
  const stale=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}`,{admin:true}),runtime));assert.equal(stale.body.history_suggestions[0].is_stale,true);assert.equal(stale.body.history_suggestions[0].authoritative.title,"Studio-authoritative title");
  const guarded=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"approve",title:"Implicit overwrite",summary:"This must not replace authority."}}),runtime));assert.equal(guarded.status,409);assert.match(guarded.body.error,/Approve and replace/);assert.equal(db.prepare("SELECT title FROM entity_activity WHERE id=?").get(activityId).title,"Studio-authoritative title");

  const replaced=await json(await handleConstructApi(request(`/api/admin/archive-notes/${noteId}/history-suggestions/${suggestionId}`,{method:"PATCH",admin:true,body:{action:"approve-replace",title:"Explicitly reapproved title",summary:"Studio deliberately replaced the authoritative wording."}}),runtime));
  assert.equal(replaced.status,200,replaced.body.error);assert.equal(replaced.body.record.activity_id,activityId);assert.equal(replaced.body.record.is_stale,false);assert.equal(db.prepare("SELECT title FROM entity_activity WHERE id=?").get(activityId).title,"Explicitly reapproved title");assert.equal(db.prepare("SELECT COUNT(*) count FROM entity_activity WHERE id=?").get(activityId).count,1);assert.equal(db.prepare("SELECT COUNT(*) count FROM entity_revisions WHERE entity_id='art-marbles' AND action='archive-note-history-approve'").get().count,2);
});

test("Archive Notes UI keeps the Apple date reminder, bounded reader, and clean export boundary",()=>{
  const studio=readFileSync(join(ROOT,"studio","archive-notes-manager.js"),"utf8"),studioStyles=readFileSync(join(ROOT,"studio","archive-notes-manager.css"),"utf8"),construct=readFileSync(join(ROOT,"studio","construct-manager.js"),"utf8"),styles=readFileSync(join(ROOT,"css","archive-notes.css"),"utf8"),page=readFileSync(join(ROOT,"archive","notes","index.html"),"utf8"),renderer=readFileSync(join(ROOT,"js","archive-note-markdown.js"),"utf8"),notesPage=readFileSync(join(ROOT,"js","archive-notes.js"),"utf8"),archivePublic=readFileSync(join(ROOT,"js","archive-public.js"),"utf8"),migration=readFileSync(join(ROOT,"migrations","0177_archive_notes.sql"),"utf8"),historyMigration=readFileSync(join(ROOT,"migrations","0184_archive_note_history_suggestions.sql"),"utf8");
  assert.match(studio,/On a Mac using upgraded iCloud Notes, click the date at the top of the note to view its Created and Last Edited dates/);assert.match(studio,/support\.apple\.com\/guide\/notes\/view-your-notes/);assert.match(studio,/source-provenance/);assert.match(studio,/Export Obsidian ZIP/);assert.match(studio,/\/api\/admin\/archive-notes\/import/);assert.match(studio,/\/api\/admin\/archive-notes\/\$\{encodeURIComponent\(note\.id\)\}\/export/);
  assert.match(studio,/data-journal-files hidden/);assert.match(studio,/multiple data-journal-files/);assert.match(studio,/pendingFingerprint/);assert.match(studio,/duplicate\$\{duplicates===1\?"":"s"\} skipped/);assert.match(studio,/data-journal-lead/);assert.match(studio,/data-journal-alt/);assert.match(studio,/data-journal-caption/);assert.match(studio,/Retry keeps completed media and attachments/);assert.match(studio,/Approve and replace/);assert.match(studio,/history-suggestions/);assert.match(studioStyles,/archive-note-history-review-card/);
  assert.match(construct,/data-dossier-journal-new/);assert.match(construct,/target_entity_id:entityId/);assert.match(construct,/Journal moments/);assert.match(construct,/Process Evidence \/ Source Materials/);
  assert.match(styles,/max-height:min\(72dvh,900px\)/);assert.match(styles,/overflow-y:auto/);assert.match(styles,/border:5px/);assert.match(styles,/archive-note-provenance/);assert.match(styles,/color:var\(--color-text-dim\)!important/);assert.match(styles,/text-transform:none!important/);assert.match(styles,/archive-note-image-dialog/);assert.match(styles,/\.archive-note-quick-card-preview\{[^}]*aspect-ratio:4\/3;[^}]*overflow:hidden/);assert.match(renderer,/data-note-image-trigger/);assert.match(renderer,/bindImageLightboxes/);assert.match(notesPage,/bindImageLightboxes\(app\)/);assert.match(archivePublic,/href="\/archive\/notes\/">Notes/);assert.match(archivePublic,/class="archive-note-quick-card-preview"/);assert.match(archivePublic,/bindImageLightboxes\(content\)/);assert.match(page,/data-archive-view="notes"/);assert.match(page,/archive-note-markdown\.js/);assert.match(migration,/archive_note_assets/);assert.match(migration,/archive_note_links/);
  assert.match(styles,/archive-journal-entry-media/);assert.match(archivePublic,/Journal moments/);assert.match(archivePublic,/Process Evidence \/ Source Materials/);assert.match(archivePublic,/list\(note\.assets\)\.slice\(\)\.sort/);assert.match(historyMigration,/CREATE TABLE archive_note_history_suggestions/);assert.match(historyMigration,/UNIQUE\(note_entity_id,target_entity_id\)/);assert.match(historyMigration,/activity_id TEXT/);
});
