import assert from "node:assert/strict";
import { readFileSync,readdirSync } from "node:fs";
import { dirname,join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { handleConstructApi } from "../functions/api/construct/_lib.js";

const ROOT=dirname(dirname(fileURLToPath(import.meta.url))),TOKEN="current-works-token";
const source=(...parts)=>readFileSync(join(ROOT,...parts),"utf8");
class Statement{constructor(db,sql,values=[]){this.db=db;this.sql=sql;this.values=values}bind(...values){return new Statement(this.db,this.sql,values)}async first(column){const row=this.db.prepare(this.sql).get(...this.values);return column?row?.[column]:row||null}async all(){return{results:this.db.prepare(this.sql).all(...this.values)}}async run(){const result=this.db.prepare(this.sql).run(...this.values);return{success:true,meta:{changes:Number(result.changes||0)}}}}
class D1{constructor(db){this.db=db}prepare(sql){return new Statement(this.db,sql)}async batch(statements){this.db.exec("BEGIN");try{const results=[];for(const statement of statements)results.push(await statement.run());this.db.exec("COMMIT");return results}catch(error){this.db.exec("ROLLBACK");throw error}}}
function database(){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const name of readdirSync(join(ROOT,"migrations")).filter(name=>name.endsWith(".sql")).sort())db.exec(source("migrations",name));return db}
const env=(db)=>({SUBMISSIONS_DB:new D1(db),SUBMISSIONS_ADMIN_TOKEN:TOKEN});
const request=(path,{method="GET",body,admin=false}={})=>new Request(`https://example.test${path}`,{method,headers:{...(body===undefined?{}:{"content-type":"application/json"}),...(admin?{authorization:`Bearer ${TOKEN}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const payload=async(response)=>({status:response.status,body:await response.json()});
function media(db,{id,entityId,privacy="public",presentation="inline",alt="A current work artifact"}){db.prepare("INSERT INTO media_assets(id,source_url,original_filename,mime_type,alt_text,privacy,state,public_presentation,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',?,'test',datetime('now'),datetime('now'))").run(id,`/assets/${id}.jpg`,`${id}.jpg`,"image/jpeg",alt,privacy,presentation);db.prepare("INSERT INTO entity_media(entity_id,media_id,role,sort_order,public_visible,created_at) VALUES(?,?,'primary',1,1,datetime('now'))").run(entityId,id)}

test("migration seeds eight ordered projects and puts Current Works first in About",()=>{const db=database(),rows=db.prepare("SELECT title,collage_slot FROM about_current_projects ORDER BY sort_order").all(),paths=db.prepare("SELECT name,route FROM construct_pathways WHERE node_id='node-about' AND state='published' ORDER BY sort_order").all(),saiel=paths.find(path=>path.route==="/about/saieldauhnsolehman/");assert.equal(rows.length,8);assert.equal(rows[0].title,"Philosophy, Politics & Economics");assert.equal(rows[6].title,"The Solehman Letters + Mindful Darkness");assert.equal(rows[7].title,"Solehman’s New Year + GREEN[FIELD]");assert.equal(rows.every(row=>row.collage_slot===0),true);assert.equal(paths[0].name,"Current Works + Projects");assert.equal(paths[0].route,"/currently");assert.equal(saiel?.name,"Saiel Dauhn Solehman");assert.equal(new Set(paths.map(path=>path.route)).size,paths.length)});

test("GREEN[FIELD] is canonical across the event, Archive, pathways, Current Works, and Scout",()=>{
  const db=database();
  const event=db.prepare("SELECT id,slug,title FROM events WHERE title='GREEN[FIELD]'").get();
  const dossier=db.prepare("SELECT archive_slug FROM archive_dossiers WHERE entity_id=?").get(event.id);
  const eventPath=db.prepare("SELECT name,route FROM construct_pathways WHERE id='path-events-01'").get();
  const merchPath=db.prepare("SELECT name,route FROM construct_pathways WHERE id='path-merch-04'").get();
  const project=db.prepare("SELECT slug,title,summary,items_json,links_json FROM about_current_projects WHERE id='current-project-events'").get();
  const scout=db.prepare("SELECT scout_brief FROM calendar_scout_profiles WHERE id='atlanta-default'").get();
  assert.deepEqual({slug:event.slug,title:event.title},{slug:"greenfield",title:"GREEN[FIELD]"});
  assert.equal(dossier.archive_slug,"greenfield");
  assert.equal(eventPath.name,"GREEN[FIELD]");
  assert.equal(eventPath.route,"/events/greenfield/");
  assert.equal(merchPath.name,"GREEN[FIELD] merch");
  assert.equal(merchPath.route,"/merch/?filter=greenfield");
  assert.equal(project.slug,"solehmans-new-year-greenfield");
  assert.equal(project.title,"Solehman’s New Year + GREEN[FIELD]");
  assert.match(project.summary,/GREEN\[FIELD\]/);
  assert.equal(JSON.parse(project.items_json)[1].title,"GREEN[FIELD]");
  assert.equal(JSON.parse(project.links_json)[1].url,"/events/greenfield/");
  assert.match(scout.scout_brief,/Future GREEN\[FIELD\] Programming/);
});

test("migration gives composite cards structured items and leaves single-focus cards in prose",()=>{const db=database(),rows=db.prepare("SELECT id,items_json FROM about_current_projects ORDER BY sort_order").all(),itemsById=new Map(rows.map(row=>[row.id,JSON.parse(row.items_json)]));assert.deepEqual(itemsById.get("current-project-academic-study"),[]);assert.deepEqual(itemsById.get("current-project-thoughtpuppet"),[]);assert.deepEqual(itemsById.get("current-project-sixwell-clothing"),[]);assert.deepEqual(itemsById.get("current-project-construct-archive").map(item=>item.title),["The Six.Well Construct","Archive"]);assert.deepEqual(itemsById.get("current-project-artpill").map(item=>item.title),["Maze Builder","Build Your Own","Special Projects"]);assert.deepEqual(itemsById.get("current-project-cultural-research").map(item=>item.title),["Signal & Symbol","Atlanta Creative Calendar","Night Planning"]);assert.deepEqual(itemsById.get("current-project-solehman-letters").map(item=>item.title),["The Solehman Letters","Mindful Darkness"]);assert.deepEqual(itemsById.get("current-project-events").map(item=>item.title),["Solehman’s New Year","GREEN[FIELD]"])});

test("Solehman Letters and Mindful Darkness belong to the Writings node",()=>{const db=database(),letters=db.prepare("SELECT p.title,p.medium_key,p.links_json,e.node_id FROM about_current_projects p JOIN content_entities e ON e.id=p.id WHERE p.id='current-project-solehman-letters'").get(),pathways=db.prepare("SELECT name,route FROM construct_pathways WHERE node_id='node-writings' ORDER BY sort_order").all(),byName=new Map(pathways.map(pathway=>[pathway.name,pathway.route]));assert.equal(letters.title,"The Solehman Letters + Mindful Darkness");assert.equal(letters.medium_key,"writings");assert.equal(letters.node_id,"node-writings");assert.deepEqual(JSON.parse(letters.links_json),[{label:"Read The Solehman Letters",url:"https://www.solehmanletters.com/"},{label:"Mindful Darkness",url:"/writings/#reading-paths"}]);assert.equal(byName.get("Mindful Darkness"),"/writings/#reading-paths");assert.equal(byName.get("THE SOLEHMAN LETTERS"),"https://www.solehmanletters.com/")});

test("Tattoo Practice fallback presents the three participatory tattoo systems and their purposes",()=>{
  const script=source("currently","current-works.js");
  for(const phrase of [
    "Participatory Tattoo Systems",
    "Active · Maze Builder, Build Your Own + Special Projects",
    "participant-led play",
    "Maze Builder —",
    "Build Your Own —",
    "Special Projects —",
    "conventional commission process",
    "url:\"/tattoos/build/maze/\"",
    "url:\"/tattoos/build/\"",
    "url:\"/tattoos/special-projects/\"",
  ]){
    assert.ok(script.includes(phrase),`missing Tattoo Practice fallback phrase: ${phrase}`);
  }
});

test("public API filters drafts and derives only visibility-safe collage media",async()=>{const db=database(),runtime=env(db);let result=await payload(await handleConstructApi(request("/api/current-projects"),runtime));assert.equal(result.status,200);assert.equal(result.body.projects.length,8);assert.deepEqual(result.body.collage,[]);db.prepare("UPDATE about_current_projects SET state='draft' WHERE id='current-project-events'").run();db.prepare("UPDATE content_entities SET visibility='internal' WHERE id='current-project-events'").run();db.prepare("UPDATE about_current_projects SET links_json=? WHERE id='current-project-thoughtpuppet'").run('[{"label":"Unsafe","url":"http://example.test"}]');media(db,{id:"media-academic",entityId:"current-project-academic-study"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:2,focal_x:18,focal_y:72}}),runtime));assert.equal(result.status,200);result=await payload(await handleConstructApi(request("/api/current-projects"),runtime));assert.equal(result.body.projects.length,7);assert.equal(result.body.projects.find(project=>project.id==="current-project-thoughtpuppet").links.length,0);assert.equal(result.body.collage.length,1);assert.deepEqual(result.body.collage[0].focal,{x:18,y:72});assert.equal(result.body.collage[0].alt,"A current work artifact")});

test("public Current Works API exposes validated structured items",async()=>{const db=database(),runtime=env(db),result=await payload(await handleConstructApi(request("/api/current-projects"),runtime)),projects=new Map(result.body.projects.map(project=>[project.id,project]));assert.equal(result.status,200);assert.deepEqual(projects.get("current-project-cultural-research").items.map(item=>item.title),["Signal & Symbol","Atlanta Creative Calendar","Night Planning"]);assert.deepEqual(projects.get("current-project-academic-study").items,[]);assert.deepEqual(projects.get("current-project-solehman-letters").items.map(item=>item.title),["The Solehman Letters","Mindful Darkness"]);assert.match(projects.get("current-project-cultural-research").items[2].description,/Include and Must Attend/);assert.equal(projects.get("current-project-solehman-letters").accent,"writings");assert.equal(projects.get("current-project-solehman-letters").links[0].url,"https://www.solehmanletters.com/")});

test("Current Works item editing requires paired titles and descriptions",async()=>{const db=database(),runtime=env(db);let result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-cultural-research",{method:"PATCH",admin:true,body:{items_json:[{title:"Night Planning"}]}}),runtime));assert.equal(result.status,400);assert.match(result.body.error,/title and description/);result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-cultural-research",{method:"PATCH",admin:true,body:{items_json:[{title:"Night Planning",description:"Build a chronological day and night plan."}]}}),runtime));assert.equal(result.status,200);assert.deepEqual(JSON.parse(db.prepare("SELECT items_json FROM about_current_projects WHERE id='current-project-cultural-research'").get().items_json),[{title:"Night Planning",description:"Build a chronological day and night plan."}])});

test("admin authorization, links, slot uniqueness, and media eligibility are enforced",async()=>{const db=database(),runtime=env(db);assert.equal((await handleConstructApi(request("/api/admin/current-projects"),runtime)).status,401);let result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{links_json:[{label:"Unsafe",url:"http://example.test"}]}}),runtime));assert.equal(result.status,400);media(db,{id:"media-private",entityId:"current-project-academic-study",privacy:"private"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime));assert.equal(result.status,409);media(db,{id:"media-academic-public",entityId:"current-project-academic-study"});assert.equal((await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime)).status,200);media(db,{id:"media-construct-public",entityId:"current-project-construct-archive"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-construct-archive",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime));assert.equal(result.status,409);assert.match(result.body.error,/already assigned/)});

test("reordering updates the complete collection only",async()=>{const db=database(),runtime=env(db),ids=db.prepare("SELECT id FROM about_current_projects ORDER BY sort_order,id").all().map(row=>row.id).reverse();assert.equal((await handleConstructApi(request("/api/admin/current-projects/reorder",{method:"POST",admin:true,body:{ids}}),runtime)).status,200);assert.equal(db.prepare("SELECT id FROM about_current_projects ORDER BY sort_order,id LIMIT 1").get().id,ids[0]);assert.equal((await handleConstructApi(request("/api/admin/current-projects/reorder",{method:"POST",admin:true,body:{ids:ids.slice(1)}}),runtime)).status,409)});

test("landing, About rail, page, and Studio preserve the agreed interaction contracts",()=>{const home=source("home","index.html"),page=source("currently","index.html"),css=source("currently","current-works.css"),script=source("currently","current-works.js"),studio=source("studio","current-works-manager.js"),about=source("about","index.html");for(const inline of [...home.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(match=>match[1]).filter(Boolean))assert.doesNotThrow(()=>new Function(inline));for(const [label,route] of [["Currently","/currently"],["Puzzle","/"],["Browse","/adventure/"]])assert.match(home,new RegExp(`href="${route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}"[^>]*>${label}`));assert.match(home,/transition: opacity 320ms ease, transform 320ms ease/);assert.match(home,/prefers-reduced-motion: reduce/);assert.match(home,/state === 'expanded'/);assert.ok(about.indexOf("Current Works")<about.indexOf("Visual language"));assert.match(page,/rel="canonical" href="\/currently"/);assert.match(page,/href="\/currently\/current-works\.css"/);assert.match(page,/src="\/js\/construct-ambient-field\.js"/);assert.match(page,/src="\/currently\/current-works\.js"/);assert.match(page,/data-current-works-eye-field/);assert.match(page,/data-current-works-eyes/);assert.match(page,/CURRENT WORKS \+ PROJECTS\./);assert.match(page,/A current view of the study, systems, objects, gatherings, and public experiments in motion\./);assert.match(page,/current-constellation-stage/);assert.match(page,/data-current-anchor-image/);assert.match(css,/grid-template-columns: minmax\(0, 1fr\) minmax\(260px, 380px\)/);assert.match(css,/\.current-works-eye-field[^}]+height: 50%/);assert.match(css,/\.current-works-eyes/);assert.match(css,/--max-width: 1440px/);assert.match(css,/border: 5px solid var\(--color-about\)/);assert.match(css,/grid-template-columns: repeat\(3/);assert.match(css,/current-project-node\[data-position="8"\]/);assert.match(script,/ConstructAmbientField\.mount/);assert.match(script,/data-current-works-eye-field/);assert.match(script,/eyeOpacity: 0\.10/);assert.match(script,/eyeTint: "#6D3D15"/);assert.match(script,/projectSlug==="artpill-tattoo-house"/);assert.match(studio,/Five-slot readiness/);assert.doesNotMatch(studio,/consent_status|consentStatus|\bConsent\b/)});

test("Currently uses the global nav and canonical About subnode labels",()=>{const page=source("currently","index.html"),home=source("home","index.html"),nav=source("js","construct-nav.js");assert.doesNotMatch(page,/class="section-nav"/);for(const value of [home,nav]){assert.match(value,/Current Works \+ Projects/);assert.match(value,/Saiel Dauhn Solehman/)}assert.match(home,/name:'Current Works \+ Projects',url:'\/currently'/);assert.match(home,/name:'Saiel Dauhn Solehman',url:'\/about\/saieldauhnsolehman\/'/);assert.match(nav,/\['Current Works \+ Projects', '\/currently'\]/);assert.match(nav,/\['Saiel Dauhn Solehman', '\/about\/saieldauhnsolehman\/'\]/)});

test("Currently introduces creative sovereignty without replacing the constellation",()=>{const page=source("currently","index.html"),css=source("currently","current-works.css");assert.match(page,/Creative sovereignty \/ in practice/);assert.match(page,/One artist-governed ecosystem\. Each work keeps its name, retains its history, and moves between forms on terms established through the practice\./);assert.ok(page.indexOf("current-sovereignty-note")<page.indexOf("current-constellation-stage"));assert.equal((page.match(/current-constellation-stage/g)||[]).length,1);assert.match(css,/\.current-sovereignty-copy/);assert.match(css,/max-width: 720px/)});

test("composite cards render circle-bulleted bold item titles while single-focus cards keep prose",()=>{const script=source("currently","current-works.js"),css=source("currently","current-works.css"),studio=source("studio","current-works-manager.js");for(const title of ["The Six.Well Construct","Archive","Maze Builder","Build Your Own","Special Projects","Signal & Symbol","Atlanta Creative Calendar","Night Planning","The Solehman Letters","Mindful Darkness","Solehman’s New Year","GREEN[FIELD]"])assert.ok(script.includes(`title:\"${title}\"`),`missing structured Current Works title: ${title}`);assert.match(script,/url:"https:\/\/www\.solehmanletters\.com\/"/);assert.match(script,/projectBodyMarkup/);assert.match(script,/<ul class=\"current-project-items\">/);assert.match(script,/<strong>\$\{escape\(item\.title\)\}<\/strong>/);assert.match(css,/\.current-project-items li::before/);assert.match(css,/border-radius: 50%/);assert.match(studio,/Structured items · maximum six/);assert.match(studio,/items_json:items/)});
