import assert from "node:assert/strict";
import { readFileSync,readdirSync } from "node:fs";
import { dirname,join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { handleConstructApi } from "../functions/api/construct/_lib.js";

const ROOT=dirname(dirname(fileURLToPath(import.meta.url))),TOKEN="current-works-token";
const source=(...parts)=>readFileSync(join(ROOT,...parts),"utf8");
class Statement{constructor(db,sql,values=[]){this.db=db;this.sql=sql;this.values=values}bind(...values){return new Statement(this.db,this.sql,values)}async first(column){const row=this.db.prepare(this.sql).get(...this.values);return column?row?.[column]:row||null}async all(){return{results:this.db.prepare(this.sql).all(...this.values)}}async run(){const result=this.db.prepare(this.sql).run(...this.values);return{success:true,meta:{changes:Number(result.changes||0)}}}}
class D1{constructor(db){this.db=db}prepare(sql){return new Statement(this.db,sql)}async batch(statements){this.db.exec("BEGIN");try{const results=[];for(const statement of statements)results.push(await statement.run());this.db.exec("COMMIT");return results}catch(error){this.db.exec("ROLLBACK");throw error}}}
function database(){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const name of readdirSync(join(ROOT,"migrations")).filter(name=>name.endsWith(".sql")).sort())db.exec(source("migrations",name));return db}
const env=(db)=>({SUBMISSIONS_DB:new D1(db),SUBMISSIONS_ADMIN_TOKEN:TOKEN});
const request=(path,{method="GET",body,admin=false}={})=>new Request(`https://example.test${path}`,{method,headers:{...(body===undefined?{}:{"content-type":"application/json"}),...(admin?{authorization:`Bearer ${TOKEN}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const payload=async(response)=>({status:response.status,body:await response.json()});
function media(db,{id,entityId,privacy="public",consent="granted",presentation="inline",alt="A current work artifact"}){db.prepare("INSERT INTO media_assets(id,source_url,original_filename,mime_type,alt_text,privacy,consent_status,state,public_presentation,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'active',?,'test',datetime('now'),datetime('now'))").run(id,`/assets/${id}.jpg`,`${id}.jpg`,"image/jpeg",alt,privacy,consent,presentation);db.prepare("INSERT INTO entity_media(entity_id,media_id,role,sort_order,public_visible,created_at) VALUES(?,?,'primary',1,1,datetime('now'))").run(entityId,id)}

test("migration seeds seven ordered projects and puts Current Works first in About",()=>{const db=database(),rows=db.prepare("SELECT title,collage_slot FROM about_current_projects ORDER BY sort_order").all(),paths=db.prepare("SELECT name,route FROM construct_pathways WHERE node_id='node-about' AND state='published' ORDER BY sort_order").all();assert.equal(rows.length,7);assert.equal(rows[0].title,"Philosophy, Politics & Economics");assert.equal(rows.every(row=>row.collage_slot===0),true);assert.equal(paths[0].name,"Current Works");assert.equal(paths[0].route,"/about/current-state/");assert.equal(new Set(paths.map(path=>path.route)).size,paths.length)});

test("public API filters drafts and derives only consent-safe collage media",async()=>{const db=database(),runtime=env(db);let result=await payload(await handleConstructApi(request("/api/current-projects"),runtime));assert.equal(result.status,200);assert.equal(result.body.projects.length,7);assert.deepEqual(result.body.collage,[]);db.prepare("UPDATE about_current_projects SET state='draft' WHERE id='current-project-events'").run();db.prepare("UPDATE content_entities SET visibility='internal' WHERE id='current-project-events'").run();db.prepare("UPDATE about_current_projects SET links_json=? WHERE id='current-project-thoughtpuppet'").run('[{"label":"Unsafe","url":"http://example.test"}]');media(db,{id:"media-academic",entityId:"current-project-academic-study"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:2,focal_x:18,focal_y:72}}),runtime));assert.equal(result.status,200);result=await payload(await handleConstructApi(request("/api/current-projects"),runtime));assert.equal(result.body.projects.length,6);assert.equal(result.body.projects.find(project=>project.id==="current-project-thoughtpuppet").links.length,0);assert.equal(result.body.collage.length,1);assert.deepEqual(result.body.collage[0].focal,{x:18,y:72});assert.equal(result.body.collage[0].alt,"A current work artifact")});

test("admin authorization, links, slot uniqueness, and media eligibility are enforced",async()=>{const db=database(),runtime=env(db);assert.equal((await handleConstructApi(request("/api/admin/current-projects"),runtime)).status,401);let result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{links_json:[{label:"Unsafe",url:"http://example.test"}]}}),runtime));assert.equal(result.status,400);media(db,{id:"media-private",entityId:"current-project-academic-study",privacy:"private"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime));assert.equal(result.status,409);media(db,{id:"media-academic-public",entityId:"current-project-academic-study"});assert.equal((await handleConstructApi(request("/api/admin/current-projects/current-project-academic-study",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime)).status,200);media(db,{id:"media-construct-public",entityId:"current-project-construct-archive"});result=await payload(await handleConstructApi(request("/api/admin/current-projects/current-project-construct-archive",{method:"PATCH",admin:true,body:{collage_slot:1}}),runtime));assert.equal(result.status,409);assert.match(result.body.error,/already assigned/)});

test("reordering updates the complete collection only",async()=>{const db=database(),runtime=env(db),ids=db.prepare("SELECT id FROM about_current_projects ORDER BY sort_order,id").all().map(row=>row.id).reverse();assert.equal((await handleConstructApi(request("/api/admin/current-projects/reorder",{method:"POST",admin:true,body:{ids}}),runtime)).status,200);assert.equal(db.prepare("SELECT id FROM about_current_projects ORDER BY sort_order,id LIMIT 1").get().id,ids[0]);assert.equal((await handleConstructApi(request("/api/admin/current-projects/reorder",{method:"POST",admin:true,body:{ids:ids.slice(1)}}),runtime)).status,409)});

test("landing, About rail, page, and Studio preserve the agreed interaction contracts",()=>{const home=source("home","index.html"),page=source("about","current-state","index.html"),css=source("about","current-state","current-works.css"),script=source("about","current-state","current-works.js"),studio=source("studio","current-works-manager.js"),about=source("about","index.html");for(const inline of [...home.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(match=>match[1]).filter(Boolean))assert.doesNotThrow(()=>new Function(inline));for(const [label,route] of [["Currently","/about/current-state/"],["Puzzle","/"],["Browse","/adventure/"]])assert.match(home,new RegExp(`href="${route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}"[^>]*>${label}`));assert.match(home,/transition: opacity 320ms ease, transform 320ms ease/);assert.match(home,/prefers-reduced-motion: reduce/);assert.match(home,/state === 'expanded'/);assert.ok(about.indexOf("Current Works")<about.indexOf("Visual language"));assert.match(page,/ABOUT \/ CURRENTLY/);assert.match(page,/CURRENT WORKS \+ PROJECTS\./);assert.match(page,/A living view of the study, systems, objects, gatherings, and public experiments moving through the Construct now\./);assert.match(css,/border: 5px solid var\(--color-about\)/);assert.match(css,/grid-template-columns: repeat\(2/);assert.match(script,/\[1,2,3,4,5\]/);assert.match(studio,/Five-slot readiness/);assert.match(studio,/consent_status/)});
