PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS archive_records (
  id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, source_event_id TEXT UNIQUE, title TEXT NOT NULL, node_label TEXT NOT NULL DEFAULT '',
  record_type TEXT NOT NULL DEFAULT 'record', room TEXT NOT NULL DEFAULT '', date_or_period TEXT NOT NULL DEFAULT '', timeline_period TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', body_html TEXT NOT NULL DEFAULT '', record_status TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','published','retired','archived')),
  why_it_matters TEXT NOT NULL DEFAULT '', source_note TEXT NOT NULL DEFAULT '', related_notes_json TEXT NOT NULL DEFAULT '[]',
  related_routes_json TEXT NOT NULL DEFAULT '[]', aggregate_attendance INTEGER NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
  FOREIGN KEY (id) REFERENCES content_entities(id) ON DELETE CASCADE,
  FOREIGN KEY (source_event_id) REFERENCES events(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS archive_collections (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',state TEXT NOT NULL DEFAULT 'draft',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(id) REFERENCES content_entities(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS archive_collection_records (collection_id TEXT NOT NULL,record_id TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,PRIMARY KEY(collection_id,record_id),FOREIGN KEY(collection_id) REFERENCES archive_collections(id) ON DELETE CASCADE,FOREIGN KEY(record_id) REFERENCES archive_records(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS people (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,bio TEXT NOT NULL DEFAULT '',privacy TEXT NOT NULL DEFAULT 'private' CHECK(privacy IN ('public','unlisted','internal','private')),state TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(id) REFERENCES content_entities(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS places (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,public_location TEXT NOT NULL DEFAULT '',private_location TEXT NOT NULL DEFAULT '',privacy TEXT NOT NULL DEFAULT 'private' CHECK(privacy IN ('public','unlisted','internal','private')),state TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(id) REFERENCES content_entities(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS archive_record_people (record_id TEXT NOT NULL,person_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT '',public_visible INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(record_id,person_id,role),FOREIGN KEY(record_id) REFERENCES archive_records(id) ON DELETE CASCADE,FOREIGN KEY(person_id) REFERENCES people(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS archive_record_places (record_id TEXT NOT NULL,place_id TEXT NOT NULL,role TEXT NOT NULL DEFAULT '',public_visible INTEGER NOT NULL DEFAULT 0,sort_order INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(record_id,place_id,role),FOREIGN KEY(record_id) REFERENCES archive_records(id) ON DELETE CASCADE,FOREIGN KEY(place_id) REFERENCES places(id) ON DELETE CASCADE);

INSERT OR IGNORE INTO content_entities (id,entity_type,node_id,visibility,search_visibility,public_at,created_by,updated_by,created_at,updated_at) VALUES
('process-archive-frame','archive_record','archive','public',1,datetime('now'),'migration-0022','migration-0022',datetime('now'),datetime('now')),
('marbles-source-thread','archive_record','archive','public',1,datetime('now'),'migration-0022','migration-0022',datetime('now'),datetime('now')),
('coparent-flash-residue','archive_record','archive','public',1,datetime('now'),'migration-0022','migration-0022',datetime('now'),datetime('now'));

INSERT OR IGNORE INTO archive_records (id,slug,title,node_label,record_type,room,date_or_period,timeline_period,summary,body,record_status,state,why_it_matters,source_note,related_routes_json,sort_order,created_at,updated_at) VALUES
('process-archive-frame','process-archive-frame','Public Archive Frame','The Six.Well Construct','process','Process','2026','now','The first public archive structure turns process, residue, older forms, and cross-medium evidence into a browsable record layer.','The archive protects the leftovers from being treated like waste. Drafts, screenshots, old labels, process images, event traces, and abandoned structures become usable record instead of noise.','active frame','published','This record marks the point where the archive stops being a placeholder and becomes a repeatable publishing system.','process-archive-frame.md','["/archive/","/about/"]',1,datetime('now'),datetime('now')),
('marbles-source-thread','marbles-source-thread','Marbles Source Thread','Thoughtpuppet / Sai Solehman','artwork','Symbols','2026','now','A painting-source record for recurring symbolic logic: dots, outlined gestures, subconscious action, and the way one work can echo into another.','This source thread tracks a symbolic relationship instead of treating each painting as an isolated object.','source thread','published','This is the kind of record that lets the archive explain lineage without overexplaining the private studio process.','marbles-source-thread.md','["/art/","/archive/"]',2,datetime('now'),datetime('now')),
('coparent-flash-residue','coparent-flash-residue','Co-Parent Flash Residue','Art.Pill Tattoo House','tattoo-flash','Works','2026','now','A flash record kept as evidence of symbolic tattoo language, availability state, and how a design can move between tattooing and archive.','Co-Parent sits in the archive as a flash record and a source-language marker.','reference','published','The record shows that tattoo flash can function as a live offer, a past reference, and a source-language artifact at the same time.','coparent-flash-residue.md','["/tattoos/","/tattoos/flash/","/archive/"]',3,datetime('now'),datetime('now'));

INSERT OR IGNORE INTO media_assets (id,source_url,original_filename,mime_type,alt_text,privacy,state,created_by,created_at,updated_at) VALUES
('media-archive-process-1','/assets/paintings/IMG_8905.jpg','IMG_8905.jpg','image/jpeg','Public archive process image','public','active','migration-0022',datetime('now'),datetime('now')),
('media-archive-process-2','/assets/paintings/PAINTING%20CONTAINER.JPG','PAINTING CONTAINER.JPG','image/jpeg','Painting container process image','public','active','migration-0022',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO entity_media VALUES ('process-archive-frame','media-archive-process-1','gallery',1,1,'','',datetime('now')),('process-archive-frame','media-archive-process-2','gallery',2,1,'','',datetime('now')),('marbles-source-thread','media-art-marbles','primary',1,1,'','',datetime('now')),('coparent-flash-residue','media-ap-standalone-001','primary',1,1,'','',datetime('now'));
