(function(){
  const tokenKey="swc_submissions_admin_token";
  let mountSequence=0;
  const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set("authorization",`Bearer ${localStorage.getItem(tokenKey)||""}`);const response=await fetch(path,{...options,headers});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Request failed (${response.status})`);return payload}
  function entityMarkup(entity){return `<span class="cm-connection-entity" style="--node-color:${esc(entity?.node?.color||"#777")}">${entity?.imageUrl?`<img src="${esc(entity.imageUrl)}" alt="">`:`<i></i>`}<span><strong>${esc(entity?.title||"Unknown entity")}</strong><small>${esc(entity?.entityType||"")} · ${esc(entity?.node?.name||"Unassigned")} · ${esc(entity?.state||"")}</small></span></span>`}
  function label(entity){return `${entity.title} [${entity.entityType} / ${entity.node.name}]`}
  async function mount(host,options={}){
    const entityId=options.entityId||"",excludedTypes=new Set(options.excludedRelationshipTypeIds||[]),excludedTargets=new Set(options.excludedTargetEntityTypes||[]),listId=`cm-entity-options-${++mountSequence}`;
    host.innerHTML='<div class="cm-notice">Loading connections…</div>';
    try{
      const [directory,typesPayload,relationsPayload]=await Promise.all([api("/api/admin/entities"),api("/api/admin/relationship-types"),api(`/api/admin/relationships${entityId?`?entity_id=${encodeURIComponent(entityId)}`:""}`)]);
      const entities=directory.records||[],types=typesPayload.records||[],relations=relationsPayload.records||[],byId=new Map(entities.map(item=>[item.id,item])),byLabel=new Map(entities.map(item=>[label(item),item.id])),targetEntities=entities.filter(item=>item.id!==entityId&&!excludedTargets.has(item.entityType)),availableTypes=types.filter(type=>type.public_visible&&!excludedTypes.has(type.id));
      const optionMarkup=list=>list.map(item=>`<option value="${esc(label(item))}"></option>`).join("");
      const fixed=entityId?byId.get(entityId):null;
      host.innerHTML=`<section class="cm-connections-workbench"><div class="cm-head"><div><h3>Connections</h3><p class="cm-summary">Search the Construct, preview both directions, then publish deliberately. New connections are private.</p></div></div><div class="cm-connection-filters"><label>Entity type<select data-filter-type><option value="">All types</option>${[...new Set(targetEntities.map(item=>item.entityType))].sort().map(value=>`<option>${esc(value)}</option>`).join("")}</select></label><label>Node<select data-filter-node><option value="">All nodes</option>${[...new Map(targetEntities.map(item=>[item.node.id,item.node])).values()].map(node=>`<option value="${esc(node.id)}">${esc(node.name)}</option>`).join("")}</select></label></div><form class="cm-form cm-editor" data-connection-form><input type="hidden" name="id"><div class="cm-form-grid"><label>Source entity<input name="source" list="${listId}" required autocomplete="off" ${fixed?"readonly":""} value="${esc(fixed?label(fixed):"")}"></label><label>Target entity<input name="target" list="${listId}" required autocomplete="off"></label><datalist id="${listId}">${optionMarkup(targetEntities)}</datalist><label>Relationship type<select name="relationship_type_id" required><option value="">Choose type</option>${availableTypes.map(type=>`<option value="${esc(type.id)}" data-forward="${esc(type.forward_label)}" data-reverse="${esc(type.reverse_label)}">${esc(type.forward_label)} / ${esc(type.reverse_label)}</option>`).join("")}</select></label><label>Order<input name="sort_order" type="number" min="0" value="0"></label><label class="wide">Internal notes<textarea name="internal_notes"></textarea></label><label class="cm-check"><input name="public_visible" type="checkbox"> Public</label></div><div class="cm-sentence-preview" data-preview>Choose two entities and a relationship type.</div><div class="cm-actions"><button class="button">Save connection</button><button class="button" type="button" data-cancel-edit hidden>Cancel edit</button></div></form><div data-lists></div>${entityId?"":`<details class="cm-type-library"><summary>Relationship type library</summary><form class="cm-form" data-type-form><div class="cm-form-grid"><label>Forward label<input name="forward_label" required></label><label>Reverse label<input name="reverse_label" required></label><label class="wide">Description<textarea name="description"></textarea></label></div><button class="button">Add type</button></form><div class="cm-type-list">${types.map(type=>`<article><span><strong>${esc(type.forward_label)}</strong> / ${esc(type.reverse_label)}<small>${type.usage_count} uses</small></span><button type="button" class="button" data-type-toggle="${esc(type.id)}">${type.public_visible?"Disable":"Enable"}</button>${Number(type.usage_count)?"":`<button type="button" class="button danger-button" data-type-delete="${esc(type.id)}">Delete</button>`}</article>`).join("")}</div></details>`}</section>`;
      if(entityId&&options.originThreads){const originHost=document.createElement("div");originHost.dataset.originThreadEditor="";host.querySelector(".cm-connection-filters")?.before(originHost);await window.OriginThreadManager?.mount(originHost,{entityId,onManage:options.onManageOriginThreads})}
      host.querySelectorAll(".cm-type-list article").forEach((article,index)=>{const row=types[index];if(!row)return;const button=document.createElement("button");button.type="button";button.className="button";button.textContent="Edit labels";button.addEventListener("click",async()=>{const forward=prompt("Forward label",row.forward_label);if(forward===null)return;const reverse=prompt("Reverse label",row.reverse_label);if(reverse===null)return;const description=prompt("Description",row.description||"");if(description===null)return;try{await api(`/api/admin/relationship-types/${encodeURIComponent(row.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({forward_label:forward,reverse_label:reverse,description})});mount(host,options)}catch(error){alert(error.message)}});article.appendChild(button)});
      const form=host.querySelector("[data-connection-form]"),source=form.elements.source,target=form.elements.target,type=form.elements.relationship_type_id,resolve=input=>byLabel.get(input.value)||byId.get(input.value)?.id||"";
      function preview(){const a=byId.get(resolve(source)),b=byId.get(resolve(target)),option=type.selectedOptions[0];host.querySelector("[data-preview]").innerHTML=a&&b&&option?.dataset.forward?`<strong>${esc(a.title)}</strong> ${esc(option.dataset.forward)} <strong>${esc(b.title)}</strong><br><strong>${esc(b.title)}</strong> ${esc(option.dataset.reverse)} <strong>${esc(a.title)}</strong>`:"Choose two entities and a relationship type."}
      function section(title,rows){return `<section class="cm-connection-list"><h4>${esc(title)} (${rows.length})</h4>${rows.map(row=>`<article class="cm-connection-row" style="--source:${esc(row.source.node.color)};--target:${esc(row.target.node.color)}">${entityMarkup(row.source)}<span class="cm-connection-label">${esc(row.forward_label)}<small>${row.public_visible?"Public":"Private"}</small></span>${entityMarkup(row.target)}<span class="cm-actions"><button type="button" class="button" data-edit="${esc(row.id)}">Edit</button><button type="button" class="button danger-button" data-delete="${esc(row.id)}">Remove</button></span></article>`).join("")||'<div class="cm-empty">No connections.</div>'}</section>`}
      const outgoing=relations.filter(row=>!entityId||row.source_entity_id===entityId),incoming=relations.filter(row=>row.target_entity_id===entityId);host.querySelector("[data-lists]").innerHTML=entityId?section("Outgoing",outgoing)+section("Incoming",incoming):section("All connections",relations);
      [source,target,type].forEach(control=>control.addEventListener("input",preview));
      function reset(){form.reset();form.elements.id.value="";if(fixed)source.value=label(fixed);host.querySelector("[data-cancel-edit]").hidden=true;preview()}
      form.addEventListener("submit",async event=>{event.preventDefault();const relationId=form.elements.id.value,payload={source_entity_id:resolve(source),target_entity_id:resolve(target),relationship_type_id:type.value,internal_notes:form.elements.internal_notes.value,sort_order:Number(form.elements.sort_order.value)||0,public_visible:form.elements.public_visible.checked};if(!payload.source_entity_id||!payload.target_entity_id)return alert("Choose entities from the search list.");try{await api(`/api/admin/relationships${relationId?`/${encodeURIComponent(relationId)}`:""}`,{method:relationId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});mount(host,options)}catch(error){alert(error.message)}});
      host.querySelector("[data-cancel-edit]").addEventListener("click",reset);
      host.addEventListener("click",async event=>{const edit=event.target.closest("[data-edit]"),remove=event.target.closest("[data-delete]"),toggle=event.target.closest("[data-type-toggle]"),deleteType=event.target.closest("[data-type-delete]");try{if(edit){const row=relations.find(item=>item.id===edit.dataset.edit);source.value=label(row.source);target.value=label(row.target);type.value=row.relationship_type_id;form.elements.id.value=row.id;form.elements.internal_notes.value=row.internal_notes||"";form.elements.sort_order.value=row.sort_order||0;form.elements.public_visible.checked=Boolean(row.public_visible);host.querySelector("[data-cancel-edit]").hidden=false;preview();form.scrollIntoView({behavior:"smooth"})}if(remove&&confirm("Remove this connection from both directions?")){await api(`/api/admin/relationships/${encodeURIComponent(remove.dataset.delete)}`,{method:"DELETE"});mount(host,options)}if(toggle){const row=types.find(item=>item.id===toggle.dataset.typeToggle);await api(`/api/admin/relationship-types/${encodeURIComponent(row.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({public_visible:!row.public_visible})});mount(host,options)}if(deleteType&&confirm("Delete this unused type?")){await api(`/api/admin/relationship-types/${encodeURIComponent(deleteType.dataset.typeDelete)}`,{method:"DELETE"});mount(host,options)}}catch(error){alert(error.message)}});
      const filter=()=>{const entityType=host.querySelector("[data-filter-type]").value,node=host.querySelector("[data-filter-node]").value;host.querySelector("datalist").innerHTML=optionMarkup(targetEntities.filter(item=>(!entityType||item.entityType===entityType)&&(!node||item.node.id===node)))};host.querySelectorAll("[data-filter-type],[data-filter-node]").forEach(control=>control.addEventListener("change",filter));
      host.querySelector("[data-type-form]")?.addEventListener("submit",async event=>{event.preventDefault();await api("/api/admin/relationship-types",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});mount(host,options)});
    }catch(error){host.innerHTML=`<div class="cm-notice" data-kind="error">${esc(error.message)}</div>`}
  }
  window.ConnectionsManager={mount};
})();
