const FIELDS = [
  ["title","Title","text"],["slug","Permanent slug","text"],["catalog_number","Catalogue number","text"],
  ["product_type","Product type","text"],["source_venture","Source venture","select"],
  ["state","Publication","publication"],["availability_state","Availability","availability"],
  ["shopify_handle","Shopify handle (optional)","text"],["image_url","Primary image URL","url"],
  ["alt_text","Image alt text","text"],["statement","Hero descriptor","textarea"],
  ["description","Product description","textarea"],["edition_text","Edition text","text"],
  ["shipping_note","Shipping note","text"],["price_note","Price note","text"],
  ["origin_title","Origin title","text"],["origin_path","Origin path","text"],
  ["origin_thumb","Origin image","text"],["origin_meta","Origin metadata","text"],
  ["options_json","Pre-Shopify options JSON","textarea"],["sort_order","Sort order","number"],
];

function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function option(value,label,current){return `<option value="${esc(value)}" ${String(current)===value?"selected":""}>${esc(label)}</option>`}
function field([name,label,type],record){const value=record?.[name]??(name==="options_json"?"{}":"");if(type==="textarea")return `<label class="mm-wide">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;if(type==="select")return `<label>${label}<select name="${name}">${option("six.well","six.well clothing",value)}${option("thoughtpuppet","thoughtpuppet",value)}${option("art.pill","art.pill Tattoo Supply",value)}</select></label>`;if(type==="publication")return `<label>${label}<select name="${name}">${["draft","published","retired","archived"].map(v=>option(v,v,value||"draft")).join("")}</select></label>`;if(type==="availability")return `<label>${label}<select name="${name}">${["coming_soon","sold_out",...(value==="available"?["available"]:[])].map(v=>option(v,v.replace("_"," "),value||"coming_soon")).join("")}</select><small>Use Launch to move Coming Soon to Available.</small></label>`;return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${name==="slug"&&record?.public_at?"readonly":""}></label>`}
function form(record={}){return `<form class="mm-form" data-merch-form data-id="${esc(record.id||"")}"><div class="mm-form-head"><div><span class="cm-section-index">${record.id?"Edit product":"New product"}</span><h3>${esc(record.title||"Studio Merch product")}</h3></div><button class="button" type="button" data-merch-cancel>Close</button></div><div class="mm-fields">${FIELDS.map(item=>field(item,record)).join("")}<label class="mm-check"><input name="notify_enabled" type="checkbox" ${Number(record.notify_enabled??1)===1?"checked":""}> Accept product launch alerts while Coming Soon</label></div><div class="cm-actions"><button class="button" type="submit">${record.id?"Save product":"Create draft"}</button><span data-merch-form-status aria-live="polite"></span></div></form>`}
function card(record){const counts=record.alert_counts||{},indicator=`${record.state} · ${String(record.availability_state).replace("_"," ")}`;return `<article class="cm-card mm-card"><div class="cm-card-head"><div><span class="cm-pill">${esc(indicator)}</span><h3>${esc(record.title)}</h3></div><span class="mm-catalog">N° ${esc(record.catalog_number||"—")}</span></div><div class="cm-meta">/${esc(record.slug)} · ${record.shopify_handle?`Shopify: ${esc(record.shopify_handle)}`:"No Shopify connection"}</div><p>${esc(record.statement||record.description||"No public description yet.")}</p><div class="mm-quiet">${Number(counts.confirmed)||0} confirmed alerts · ${Number(counts.pending)||0} pending</div><div class="cm-actions"><button class="button" type="button" data-merch-edit="${esc(record.id)}">Edit</button>${record.state==="published"?`<a class="button" href="${esc(record.route)}" target="_blank" rel="noopener">Open page</a>`:""}${record.availability_state==="coming_soon"?`<button class="button" type="button" data-merch-preview="${esc(record.id)}">Launch review</button>`:""}</div></article>`}
function reconciliation(data){const items=data.shopifyOnly||[];return `<section class="mm-panel"><div class="mm-panel-head"><div><span class="cm-section-index">Shopify reconciliation</span><h3>Commerce connections</h3></div><span class="mm-quiet">${data.shopifyAvailable?"Shopify connected":esc(data.shopifyError||"Shopify unavailable")}</span></div>${data.brokenHandles?.length?`<p class="cm-notice" data-kind="error">Broken handles: ${data.brokenHandles.map(esc).join(", ")}</p>`:""}${items.length?`<div class="mm-reconcile-list">${items.map(item=>`<div><span><strong>${esc(item.title)}</strong><small>${esc(item.handle)}</small></span><button class="button" type="button" data-merch-import="${esc(item.handle)}">Import as draft</button></div>`).join("")}</div>`:`<p class="mm-quiet">No Shopify-only tagged products.</p>`}</section>`}

async function templatePanel(api){const keys=[["merch_launch_confirmation","Product alert confirmation"],["merch_launch_available","Product launch notice"]];const results=await Promise.all(keys.map(async([key,label])=>[key,label,await api(`/api/admin/merch-workflow/templates/${key}`)]));return `<section class="mm-panel"><span class="cm-section-index">Email templates</span><h3>Six.Well Merch messages</h3><p class="mm-quiet">Save a draft, preview it in Launch review, then publish it before sending.</p>${results.map(([key,label,payload])=>{const current=payload.draft?.content||payload.published?.content||payload.defaults,base=payload.draft?.revision||payload.published?.revision||0;return `<details><summary>${esc(label)} <span class="mm-quiet">published r${payload.published?.revision||0}${payload.draft?` · draft r${payload.draft.revision}`:""}</span></summary><form data-merch-template="${key}" data-base-revision="${base}" data-draft-revision="${payload.draft?.revision||0}"><label>Subject<input name="subject" value="${esc(current.subject)}"></label><label>Preheader<input name="preheader" value="${esc(current.preheader)}"></label><label>Heading<input name="heading" value="${esc(current.heading)}"></label><label>Body<textarea name="body">${esc(current.body)}</textarea></label><label>Button label<input name="buttonLabel" value="${esc(current.buttonLabel)}"></label><label>Footer<textarea name="footer">${esc(current.footer)}</textarea></label><div class="cm-actions"><button class="button" type="submit">Save draft</button>${payload.draft?`<button class="button" type="button" data-template-publish="${key}" data-revision="${payload.draft.revision}">Publish draft</button>`:""}<span data-template-status aria-live="polite"></span></div></form></details>`}).join("")}</section>`}

function launchPanel(payload){const p=payload.product;return `<section class="mm-launch" data-launch-panel><div class="mm-panel-head"><div><span class="cm-section-index">Launch review</span><h3>${esc(p.title)}</h3></div><button class="button" type="button" data-launch-close>Close</button></div><div class="mm-readiness ${payload.ready?"is-ready":""}"><strong>${payload.ready?"Ready for explicit launch":"Not ready"}</strong><span>${payload.audienceCount} confirmed alert${payload.audienceCount===1?"":"s"}</span></div>${payload.reasons?.length?`<ul>${payload.reasons.map(reason=>`<li>${esc(reason)}</li>`).join("")}</ul>`:""}<div class="mm-preview-meta"><strong>${esc(payload.preview.subject)}</strong><span>Template revision ${payload.templateRevision}</span></div><iframe title="Launch email preview" srcdoc="${esc(payload.preview.html)}"></iframe><div class="cm-actions"><button class="button" type="button" data-launch-confirm="${esc(p.id)}" data-updated-at="${esc(p.updated_at)}" ${payload.ready?"":"disabled"}>Confirm availability and send ${payload.audienceCount} alert${payload.audienceCount===1?"":"s"}</button><span data-launch-status aria-live="polite"></span></div></section>`}

function values(form){const data=new FormData(form),body={};for(const [name,value] of data.entries())body[name]=value;body.notify_enabled=form.elements.notify_enabled?.checked?1:0;body.sort_order=Number(body.sort_order)||0;try{body.options_json=JSON.parse(body.options_json||"{}")}catch{throw new Error("Pre-Shopify options must be valid JSON.")}return body}

export async function mount(host,api,setStatus){
  if(!document.querySelector('link[href="/studio/merch-manager.css"]')){const link=document.createElement("link");link.rel="stylesheet";link.href="/studio/merch-manager.css";document.head.appendChild(link)}
  host.innerHTML='<section class="construct-manager"><p>Loading Merch workflow…</p></section>';
  async function paint(){try{const [payload,templates]=await Promise.all([api("/api/admin/merch-workflow"),templatePanel(api)]);host.innerHTML=`<section class="construct-manager mm-workspace"><div class="cm-head"><div><h2>Merch Products</h2><p class="cm-summary">Studio owns product identity, publication, Coming Soon pages, and launch alerts. Connecting Shopify never launches or sends anything.</p></div><button class="button" type="button" data-merch-new>New product</button></div><div data-merch-editor></div>${reconciliation(payload.reconciliation||{})}<div class="cm-grid">${(payload.records||[]).map(card).join("")||'<div class="cm-empty">No Merch records.</div>'}</div>${templates}<div data-merch-launch></div></section>`;bind(payload)}catch(error){host.innerHTML=`<section class="construct-manager"><div class="cm-notice" data-kind="error">${esc(error.message)}</div></section>`}}
  function bind(payload){const shell=host.querySelector(".mm-workspace"),editor=shell.querySelector("[data-merch-editor]"),launch=shell.querySelector("[data-merch-launch]"),records=payload.records||[];
    shell.addEventListener("click",async event=>{const fresh=event.target.closest("[data-merch-new]"),edit=event.target.closest("[data-merch-edit]"),cancel=event.target.closest("[data-merch-cancel]"),importButton=event.target.closest("[data-merch-import]"),preview=event.target.closest("[data-merch-preview]"),close=event.target.closest("[data-launch-close]"),confirmButton=event.target.closest("[data-launch-confirm]"),publish=event.target.closest("[data-template-publish]");
      if(fresh||edit){editor.innerHTML=form(edit?records.find(record=>record.id===edit.dataset.merchEdit):{});editor.querySelector("input")?.focus();return}
      if(cancel){editor.innerHTML="";return}
      if(importButton){try{importButton.disabled=true;await api("/api/admin/merch-workflow/import-shopify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle:importButton.dataset.merchImport})});setStatus("Shopify product imported as a private draft");await paint()}catch(error){setStatus(error.message);importButton.disabled=false}return}
      if(preview){try{launch.innerHTML='<p>Checking launch readiness…</p>';launch.innerHTML=launchPanel(await api(`/api/admin/merch-workflow/${encodeURIComponent(preview.dataset.merchPreview)}/preview`));launch.scrollIntoView({behavior:"smooth",block:"start"})}catch(error){launch.innerHTML=`<div class="cm-notice" data-kind="error">${esc(error.message)}</div>`}return}
      if(close){launch.innerHTML="";return}
      if(confirmButton){if(!window.confirm("Launch this product now and send the one-time alert to the confirmed audience? This cannot be undone."))return;const output=launch.querySelector("[data-launch-status]");try{confirmButton.disabled=true;output.textContent="Launching and sending…";const result=await api(`/api/admin/merch-workflow/${encodeURIComponent(confirmButton.dataset.launchConfirm)}/launch`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true,expectedUpdatedAt:confirmButton.dataset.updatedAt})});setStatus(`Product launched · ${result.sent} sent · ${result.failed} failed`);await paint()}catch(error){output.textContent=error.message;confirmButton.disabled=false}return}
      if(publish){if(!window.confirm("Publish this email draft for future Merch messages?"))return;const form=publish.closest("form"),output=form.querySelector("[data-template-status]");try{await api(`/api/admin/merch-workflow/templates/${publish.dataset.templatePublish}/publish`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({revision:Number(publish.dataset.revision)})});setStatus("Merch email template published");await paint()}catch(error){output.textContent=error.message}return}
    });
    shell.addEventListener("submit",async event=>{const productForm=event.target.closest("[data-merch-form]"),templateForm=event.target.closest("[data-merch-template]");if(productForm){event.preventDefault();const output=productForm.querySelector("[data-merch-form-status]");try{output.textContent="Saving…";const id=productForm.dataset.id;await api(`/api/admin/merch-workflow${id?`/${encodeURIComponent(id)}`:""}`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(values(productForm))});setStatus(id?"Merch product saved":"Private Merch draft created");await paint()}catch(error){output.textContent=error.message}return}if(templateForm){event.preventDefault();const output=templateForm.querySelector("[data-template-status]"),data=new FormData(templateForm),content=Object.fromEntries(data.entries());try{output.textContent="Saving draft…";await api(`/api/admin/merch-workflow/templates/${templateForm.dataset.merchTemplate}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({baseRevision:Number(templateForm.dataset.baseRevision),content})});setStatus("Merch email draft saved");await paint()}catch(error){output.textContent=error.message}}})
  }
  await paint()
}
