const FIELDS = [
  ["title","Title","text"],["slug","Permanent slug","text"],["catalog_number","Catalogue number","text"],
  ["product_type","Product type","text"],["source_venture","Source venture","select"],
  ["state","Publication","publication"],["availability_state","Availability","availability"],
  ["shopify_handle","Shopify handle (optional)","text"],["image_url","Primary image URL","url"],
  ["alt_text","Image alt text","text"],["statement","Hero descriptor","textarea"],
  ["description","Product description","textarea"],["edition_text","Edition text","text"],
  ["shipping_note","Shipping note","text"],["price_note","Price note","text"],
  ["origin_title","Origin title","text"],["origin_path","Origin path","text"],
  ["origin_thumb","Origin image","text"],["origin_meta","Origin metadata","text"],
  ["options_json","Pre-Shopify options JSON","textarea"],["sort_order","Sort order","number"],
];
const TOKEN_KEY="swc_submissions_admin_token";
const IMAGE_TYPES=new Set(["image/jpeg","image/png","image/webp","image/gif"]);
const previewUrls=new Set();

function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function option(value,label,current){return `<option value="${esc(value)}" ${String(current)===value?"selected":""}>${esc(label)}</option>`}
function field([name,label,type],record){const value=record?.[name]??(name==="options_json"?"{}":"");if(type==="textarea")return `<label class="mm-wide">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;if(type==="select")return `<label>${label}<select name="${name}">${option("six.well","six.well clothing",value)}${option("thoughtpuppet","thoughtpuppet",value)}${option("art.pill","art.pill Tattoo Supply",value)}</select></label>`;if(type==="publication")return `<label>${label}<select name="${name}">${["draft","published","retired","archived"].map(v=>option(v,v,value||"draft")).join("")}</select></label>`;if(type==="availability")return `<label>${label}<select name="${name}">${["coming_soon","sold_out",...(value==="available"?["available"]:[])].map(v=>option(v,v.replace("_"," "),value||"coming_soon")).join("")}</select><small>Use Launch to move Coming Soon to Available.</small></label>`;return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${name==="slug"&&record?.public_at?"readonly":""}></label>`}
function mediaEditor(record={}){const media=record.media||[];return `<section class="mm-media mm-wide"><div class="mm-media-head"><div><span class="cm-section-index">Product media</span><h4>Images</h4></div><span class="mm-quiet">${media.length} attached</span></div><p class="mm-quiet">Upload JPEG, PNG, WebP, or GIF files up to 15 MB each. The first image becomes primary; additional images form the ordered product gallery.</p><label class="mm-media-upload">Upload product images<input name="product_images" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple></label>${media.length?`<div class="mm-media-grid">${media.map((item,index)=>`<article class="mm-media-item" data-merch-media-id="${esc(item.id)}" data-role="${esc(item.role)}"><div class="mm-media-preview"><img data-merch-media-preview="${esc(item.id)}" alt="${esc(item.altText||record.alt_text||record.title||"Product image")}"></div><div class="mm-media-copy"><span class="cm-pill">${item.role==="primary"?"Primary image":`Gallery ${index}`}</span><small>${esc(item.filename||"Uploaded image")}</small><label>Image alt text<input data-merch-media-alt value="${esc(item.altText||"")}"></label><div class="cm-actions"><button class="button" type="button" data-merch-media-action="save">Save alt text</button>${item.role!=="primary"?'<button class="button" type="button" data-merch-media-action="primary">Make primary</button><button class="button" type="button" data-merch-media-action="up">Move up</button><button class="button" type="button" data-merch-media-action="down">Move down</button>':""}<button class="button danger-button" type="button" data-merch-media-action="remove">Remove</button></div></div></article>`).join("")}</div>`:""}<span data-merch-upload-status aria-live="polite"></span></section>`}
function form(record={}){return `<form class="mm-form" data-merch-form data-id="${esc(record.id||"")}"><div class="mm-form-head"><div><span class="cm-section-index">${record.id?"Edit product":"New product"}</span><h3>${esc(record.title||"Studio Merch product")}</h3></div><button class="button" type="button" data-merch-cancel>Close</button></div><div class="mm-fields">${FIELDS.map(item=>field(item,record)).join("")}${mediaEditor(record)}<label class="mm-check"><input name="notify_enabled" type="checkbox" ${Number(record.notify_enabled??1)===1?"checked":""}> Accept product launch alerts while Coming Soon</label></div><div class="cm-actions"><button class="button" type="submit">${record.id?"Save product":"Create draft"}</button><span data-merch-form-status aria-live="polite"></span></div></form>`}
function card(record){const counts=record.alert_counts||{},indicator=`${record.state} · ${String(record.availability_state).replace("_"," ")}`;return `<article class="cm-card mm-card"><div class="cm-card-head"><div><span class="cm-pill">${esc(indicator)}</span><h3>${esc(record.title)}</h3></div><span class="mm-catalog">N° ${esc(record.catalog_number||"—")}</span></div><div class="cm-meta">/${esc(record.slug)} · ${record.shopify_handle?`Shopify: ${esc(record.shopify_handle)}`:"No Shopify connection"}</div><p>${esc(record.statement||record.description||"No public description yet.")}</p><div class="mm-quiet">${Number(counts.confirmed)||0} confirmed alerts · ${Number(counts.pending)||0} pending</div><div class="cm-actions"><button class="button" type="button" data-merch-edit="${esc(record.id)}">Edit</button>${record.state==="published"?`<a class="button" href="${esc(record.route)}" target="_blank" rel="noopener">Open page</a>`:""}${record.availability_state==="coming_soon"?`<button class="button" type="button" data-merch-preview="${esc(record.id)}">Launch review</button>`:""}</div></article>`}
function reconciliation(data){const items=data.shopifyOnly||[];return `<section class="mm-panel"><div class="mm-panel-head"><div><span class="cm-section-index">Shopify reconciliation</span><h3>Commerce connections</h3></div><span class="mm-quiet">${data.shopifyAvailable?"Shopify connected":esc(data.shopifyError||"Shopify unavailable")}</span></div>${data.brokenHandles?.length?`<p class="cm-notice" data-kind="error">Broken handles: ${data.brokenHandles.map(esc).join(", ")}</p>`:""}${items.length?`<div class="mm-reconcile-list">${items.map(item=>`<div><span><strong>${esc(item.title)}</strong><small>${esc(item.handle)}</small></span><button class="button" type="button" data-merch-import="${esc(item.handle)}">Import as draft</button></div>`).join("")}</div>`:`<p class="mm-quiet">No Shopify-only tagged products.</p>`}</section>`}

async function templatePanel(api){const keys=[["merch_launch_confirmation","Product alert confirmation"],["merch_launch_available","Product launch notice"]];const results=await Promise.all(keys.map(async([key,label])=>[key,label,await api(`/api/admin/merch-workflow/templates/${key}`)]));return `<section class="mm-panel"><span class="cm-section-index">Email templates</span><h3>Six.Well Merch messages</h3><p class="mm-quiet">Save a draft, preview it in Launch review, then publish it before sending.</p>${results.map(([key,label,payload])=>{const current=payload.draft?.content||payload.published?.content||payload.defaults,base=payload.draft?.revision||payload.published?.revision||0;return `<details><summary>${esc(label)} <span class="mm-quiet">published r${payload.published?.revision||0}${payload.draft?` · draft r${payload.draft.revision}`:""}</span></summary><form data-merch-template="${key}" data-base-revision="${base}" data-draft-revision="${payload.draft?.revision||0}"><label>Subject<input name="subject" value="${esc(current.subject)}"></label><label>Preheader<input name="preheader" value="${esc(current.preheader)}"></label><label>Heading<input name="heading" value="${esc(current.heading)}"></label><label>Body<textarea name="body">${esc(current.body)}</textarea></label><label>Button label<input name="buttonLabel" value="${esc(current.buttonLabel)}"></label><label>Footer<textarea name="footer">${esc(current.footer)}</textarea></label><div class="cm-actions"><button class="button" type="submit">Save draft</button>${payload.draft?`<button class="button" type="button" data-template-publish="${key}" data-revision="${payload.draft.revision}">Publish draft</button>`:""}<span data-template-status aria-live="polite"></span></div></form></details>`}).join("")}</section>`}

function launchPanel(payload){const p=payload.product;return `<section class="mm-launch" data-launch-panel><div class="mm-panel-head"><div><span class="cm-section-index">Launch review</span><h3>${esc(p.title)}</h3></div><button class="button" type="button" data-launch-close>Close</button></div><div class="mm-readiness ${payload.ready?"is-ready":""}"><strong>${payload.ready?"Ready for explicit launch":"Not ready"}</strong><span>${payload.audienceCount} confirmed alert${payload.audienceCount===1?"":"s"}</span></div>${payload.reasons?.length?`<ul>${payload.reasons.map(reason=>`<li>${esc(reason)}</li>`).join("")}</ul>`:""}<div class="mm-preview-meta"><strong>${esc(payload.preview.subject)}</strong><span>Template revision ${payload.templateRevision}</span></div><iframe title="Launch email preview" srcdoc="${esc(payload.preview.html)}"></iframe><div class="cm-actions"><button class="button" type="button" data-launch-confirm="${esc(p.id)}" data-updated-at="${esc(p.updated_at)}" ${payload.ready?"":"disabled"}>Confirm availability and send ${payload.audienceCount} alert${payload.audienceCount===1?"":"s"}</button><span data-launch-status aria-live="polite"></span></div></section>`}

function values(form){const data=new FormData(form),body={};for(const [name,value] of data.entries()){if(value instanceof File)continue;body[name]=value}body.notify_enabled=form.elements.notify_enabled?.checked?1:0;body.sort_order=Number(body.sort_order)||0;try{body.options_json=JSON.parse(body.options_json||"{}")}catch{throw new Error("Pre-Shopify options must be valid JSON.")}return body}
function validateProductImages(files){for(const file of files){if(!IMAGE_TYPES.has(file.type))throw new Error(`${file.name}: use JPEG, PNG, WebP, or GIF.`);if(file.size>15*1024*1024)throw new Error(`${file.name}: exceeds 15 MB.`)}}
function clearMediaPreviews(){previewUrls.forEach(url=>URL.revokeObjectURL(url));previewUrls.clear()}
async function hydrateMediaPreviews(scope){clearMediaPreviews();await Promise.all([...scope.querySelectorAll("[data-merch-media-preview]")].map(async image=>{try{const response=await fetch(`/api/admin/media/${encodeURIComponent(image.dataset.merchMediaPreview)}/file`,{headers:{authorization:`Bearer ${localStorage.getItem(TOKEN_KEY)||""}`},cache:"no-store"});if(!response.ok)throw new Error("Preview unavailable");const url=URL.createObjectURL(await response.blob());previewUrls.add(url);image.src=url}catch{image.hidden=true}}))}
async function uploadProductImages(api,entityId,files,altText,existingMedia=[],output){validateProductImages(files);let hasPrimary=existingMedia.some(item=>item.role==="primary"),sortOrder=Math.max(0,...existingMedia.map(item=>Number(item.sortOrder)||0));for(let index=0;index<files.length;index++){const file=files[index],role=hasPrimary?"gallery":"primary",attachmentSort=role==="primary"?1:Math.max(2,sortOrder+1);if(output)output.textContent=`Uploading ${index+1} of ${files.length}: ${file.name}`;const upload=new FormData();upload.append("file",file);upload.append("alt_text",altText);upload.append("privacy","public");upload.append("consent_status","not-required");upload.append("public_presentation","inline");const uploaded=await api("/api/admin/media",{method:"POST",body:upload}),mediaId=uploaded.record?.id;if(!mediaId)throw new Error(`${file.name} uploaded without a media ID.`);try{await api(`/api/admin/entities/${encodeURIComponent(entityId)}/media`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({media_id:mediaId,role,sort_order:attachmentSort,public_visible:true,alt_text_override:altText})})}catch(error){try{await api(`/api/admin/media/${encodeURIComponent(mediaId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({state:"archived"})})}catch{}throw error}sortOrder=Math.max(sortOrder,attachmentSort);hasPrimary=true}if(output)output.textContent=`${files.length} product image${files.length===1?"":"s"} uploaded and attached.`}

export async function mount(host,api,setStatus){
  if(!document.querySelector('link[href^="/studio/merch-manager.css"]')){const link=document.createElement("link");link.rel="stylesheet";link.href="/studio/merch-manager.css?v=20260806-product-media";document.head.appendChild(link)}
  host.innerHTML='<section class="construct-manager"><p>Loading Merch workflow…</p></section>';
  let activeEditorId="";

  async function paint(){
    clearMediaPreviews();
    try{
      const [payload,templates]=await Promise.all([api("/api/admin/merch-workflow"),templatePanel(api)]),records=payload.records||[],activeRecord=activeEditorId==="new"?{}:records.find(record=>record.id===activeEditorId);
      if(activeEditorId&&activeEditorId!=="new"&&!activeRecord)activeEditorId="";
      host.innerHTML=`<section class="construct-manager mm-workspace"><div class="cm-head"><div><h2>Merch Products</h2><p class="cm-summary">Studio owns product identity, publication, Coming Soon pages, and launch alerts. Connecting Shopify never launches or sends anything.</p></div><button class="button" type="button" data-merch-new>New product</button></div><div data-merch-editor>${activeEditorId?form(activeRecord||{}):""}</div>${reconciliation(payload.reconciliation||{})}<div class="cm-grid">${records.map(card).join("")||'<div class="cm-empty">No Merch records.</div>'}</div>${templates}<div data-merch-launch></div></section>`;
      bind(payload);
      if(activeEditorId)await hydrateMediaPreviews(host.querySelector("[data-merch-editor]"));
    }catch(error){host.innerHTML=`<section class="construct-manager"><div class="cm-notice" data-kind="error">${esc(error.message)}</div></section>`}
  }

  function bind(payload){
    const shell=host.querySelector(".mm-workspace"),editor=shell.querySelector("[data-merch-editor]"),launch=shell.querySelector("[data-merch-launch]"),records=payload.records||[];
    shell.addEventListener("click",async event=>{
      const fresh=event.target.closest("[data-merch-new]"),edit=event.target.closest("[data-merch-edit]"),cancel=event.target.closest("[data-merch-cancel]"),mediaButton=event.target.closest("[data-merch-media-action]"),importButton=event.target.closest("[data-merch-import]"),preview=event.target.closest("[data-merch-preview]"),close=event.target.closest("[data-launch-close]"),confirmButton=event.target.closest("[data-launch-confirm]"),publish=event.target.closest("[data-template-publish]");
      if(fresh||edit){activeEditorId=edit?edit.dataset.merchEdit:"new";const record=edit?records.find(item=>item.id===activeEditorId):{};editor.innerHTML=form(record||{});await hydrateMediaPreviews(editor);editor.querySelector("input")?.focus();return}
      if(cancel){activeEditorId="";clearMediaPreviews();editor.innerHTML="";return}
      if(mediaButton){
        const productForm=mediaButton.closest("[data-merch-form]"),recordId=productForm?.dataset.id,item=mediaButton.closest("[data-merch-media-id]"),mediaId=item?.dataset.merchMediaId,record=records.find(entry=>entry.id===recordId),action=mediaButton.dataset.merchMediaAction;
        if(!recordId||!mediaId||!record)return;
        const endpoint=`/api/admin/entities/${encodeURIComponent(recordId)}/media/${encodeURIComponent(mediaId)}`;
        try{
          mediaButton.disabled=true;
          if(action==="save")await api(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({alt_text_override:item.querySelector("[data-merch-media-alt]")?.value||""})});
          else if(action==="primary")await api(endpoint,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({role:"primary",sort_order:1,public_visible:true})});
          else if(action==="remove"){if(!window.confirm("Remove this image from the product? The stored media remains recoverable.")){mediaButton.disabled=false;return}await api(endpoint,{method:"DELETE"})}
          else if(action==="up"||action==="down"){
            const gallery=(record.media||[]).filter(media=>media.role!=="primary"),from=gallery.findIndex(media=>media.id===mediaId),to=action==="up"?from-1:from+1;
            if(from<0||to<0||to>=gallery.length){mediaButton.disabled=false;return}
            [gallery[from],gallery[to]]=[gallery[to],gallery[from]];
            for(const [index,media] of gallery.entries())await api(`/api/admin/entities/${encodeURIComponent(recordId)}/media/${encodeURIComponent(media.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sort_order:index+2})});
          }else return;
          setStatus(action==="remove"?"Product image removed":action==="primary"?"Primary product image changed":action==="save"?"Image alt text saved":"Product gallery reordered");
          activeEditorId=recordId;await paint();
        }catch(error){setStatus(error.message);mediaButton.disabled=false}
        return;
      }
      if(importButton){try{importButton.disabled=true;await api("/api/admin/merch-workflow/import-shopify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle:importButton.dataset.merchImport})});setStatus("Shopify product imported as a private draft");await paint()}catch(error){setStatus(error.message);importButton.disabled=false}return}
      if(preview){try{launch.innerHTML='<p>Checking launch readiness…</p>';launch.innerHTML=launchPanel(await api(`/api/admin/merch-workflow/${encodeURIComponent(preview.dataset.merchPreview)}/preview`));launch.scrollIntoView({behavior:"smooth",block:"start"})}catch(error){launch.innerHTML=`<div class="cm-notice" data-kind="error">${esc(error.message)}</div>`}return}
      if(close){launch.innerHTML="";return}
      if(confirmButton){if(!window.confirm("Launch this product now and send the one-time alert to the confirmed audience? This cannot be undone."))return;const output=launch.querySelector("[data-launch-status]");try{confirmButton.disabled=true;output.textContent="Launching and sending…";const result=await api(`/api/admin/merch-workflow/${encodeURIComponent(confirmButton.dataset.launchConfirm)}/launch`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true,expectedUpdatedAt:confirmButton.dataset.updatedAt})});setStatus(`Product launched · ${result.sent} sent · ${result.failed} failed`);await paint()}catch(error){output.textContent=error.message;confirmButton.disabled=false}return}
      if(publish){if(!window.confirm("Publish this email draft for future Merch messages?"))return;const templateForm=publish.closest("form"),output=templateForm.querySelector("[data-template-status]");try{await api(`/api/admin/merch-workflow/templates/${publish.dataset.templatePublish}/publish`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({revision:Number(publish.dataset.revision)})});setStatus("Merch email template published");await paint()}catch(error){output.textContent=error.message}return}
    });

    shell.addEventListener("submit",async event=>{
      const productForm=event.target.closest("[data-merch-form]"),templateForm=event.target.closest("[data-merch-template]");
      if(productForm){
        event.preventDefault();
        const output=productForm.querySelector("[data-merch-form-status]"),uploadOutput=productForm.querySelector("[data-merch-upload-status]"),files=[...(productForm.elements.product_images?.files||[])],body=values(productForm),before=records.find(record=>record.id===productForm.dataset.id);
        try{
          validateProductImages(files);output.textContent="Saving…";
          let id=productForm.dataset.id;
          const saved=await api(`/api/admin/merch-workflow${id?`/${encodeURIComponent(id)}`:""}`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
          id=id||saved.record?.id;if(!id)throw new Error("The Merch draft was created without an entity ID.");
          productForm.dataset.id=id;activeEditorId=id;
          if(files.length)await uploadProductImages(api,id,files,body.alt_text||body.title||"Product image",before?.media||[],uploadOutput);
          setStatus(files.length?"Merch product and images saved":before?"Merch product saved":"Private Merch draft created");activeEditorId="";await paint();
        }catch(error){output.textContent=error.message}
        return;
      }
      if(templateForm){event.preventDefault();const output=templateForm.querySelector("[data-template-status]"),data=new FormData(templateForm),content=Object.fromEntries(data.entries());try{output.textContent="Saving draft…";await api(`/api/admin/merch-workflow/templates/${templateForm.dataset.merchTemplate}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({baseRevision:Number(templateForm.dataset.baseRevision),content})});setStatus("Merch email draft saved");await paint()}catch(error){output.textContent=error.message}}
    });
  }
  await paint();
}
